### ISSUE TITLE
api request error 

### ISSUE THREAD

**Issue by Croie** [serengil/deepface#1003]
the request parameter is a base64 image: 

[2024-02-04 13:59:24,982] ERROR in app: Exception on /analyze [POST]
Traceback (most recent call last):
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/app.py", line 1183, in make_response
    rv = self.json.response(rv)
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/andy/deepface/.venv/lib/python3.10/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type int32 is not JSON serializable

What needs to be modified?

**Comment by serengil** [comment]
I am currently working on this bug, will be sorted soon

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1004

**Comment by serengil** [comment]
This change is not published in pip yet. You can use source code instead of pip package until a new release published.
