### ISSUE TITLE
NoneType' object has no attribute 'groups' when using YoloV8 on deepface==0.0.84

### ISSUE THREAD

**Issue by gbaufake** [serengil/deepface#1022]
Hi @serengil,

Is there an issue when analyzing with Yolo v8?

code sample:
`analysis = DeepFace.analyze(img, actions=('emotion'), enforce_detection=False, detector_backend=['yolo_, silent=True)`

Logs:
```
2024-02-14 03:48:24,079 [Thread-14 (analyze_video_with_backend)] INFO: {"level": 20, "message": "Detector processed frames", "detector_backend": "yolov8", "processed_frames": 100, "total_frames": 2568}
2024-02-14 03:48:25,791 [Thread-14 (analyze_video_with_backend)] ERROR: {"level": 40, "message": "Error in DeepFace Analysis", "error_detail": "'NoneType' object has no attribute 'groups'"}
```

I could not find anywhere on the code that groups might be used.

**Comment by serengil** [comment]
Need detailed exception message please

**Comment by serengil** [comment]
When I test that backend as

```python
DeepFace.analyze(img_path=img_path, detector_backend="yolov8")
```

Then I am having a successful response.

```json
[{'emotion': {'angry': 0.27702577454904015,
   'disgust': 1.6584374963028672e-06,
   'fear': 5.269103613165452e-05,
   'happy': 58.46902829039434,
   'sad': 0.10684493573024102,
   'surprise': 0.004627124696059116,
   'neutral': 41.14242388515757},
  'dominant_emotion': 'happy',
  'region': {'x': 233, 'y': 79, 'w': 152, 'h': 216},
  'face_confidence': 0.863529622554779,
  'age': 30,
  'gender': {'Woman': 99.9902606010437, 'Man': 0.009742558904690668},
  'dominant_gender': 'Woman',
  'race': {'asian': 0.2046308602172649,
   'indian': 0.3006282674523155,
   'black': 0.02210449442703989,
   'white': 83.31937094446248,
   'middle eastern': 7.54583746468052,
   'latino hispanic': 8.607432014193058},
  'dominant_race': 'white'}]
```

So, your case may be related to the input image you are feeding (share with me if it is not private), or depending on your customization.

**Comment by serengil** [comment]
That error message should come from regex, and regex is not being used in deepface. You may get it from something different than deepface?

**Comment by serengil** [comment]
Closed because exception message is not coming from deepface

**Comment by Any-Winter-4079** [comment]
Here's a bit more information about the error:

```
Traceback (most recent call last):
  File "project/face_recognition/deepface_library/find_match.py", line 32, in <module>
    dfs = DeepFace.find(img_path=test_image_path,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/DeepFace.py", line 296, in find
    return recognition.find(
           ^^^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/modules/recognition.py", line 209, in find
    source_objs = detection.extract_faces(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/modules/detection.py", line 84, in extract_faces
    face_objs = DetectorWrapper.detect_faces(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/detectors/DetectorWrapper.py", line 82, in detect_faces
    face_detector: Detector = build_model(detector_backend)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/detectors/DetectorWrapper.py", line 50, in build_model
    face_detector = face_detector()
                    ^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/detectors/Yolo.py", line 25, in __init__
    self.model = self.build_model()
                 ^^^^^^^^^^^^^^^^^^
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/deepface/detectors/Yolo.py", line 47, in build_model
    gdown.download(WEIGHT_URL, weight_path, quiet=False)
  File "project/tensorflow-metal-test/lib/python3.11/site-packages/gdown/download.py", line 259, in download
    filename_from_url = m.groups()[0]
                        ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by Any-Winter-4079** [comment]
A hack to solve this:
The weights come from here: 
https://drive.google.com/uc?id=1qcr9DbgsX3ryrz2uU8w4Xm3cOrRywXqb

You can download them and put them on your equivalent of this path:
`/Users/myself/.deepface/weights/yolov8n-face.pt`

To know your path, print it in [Yolo.py](https://github.com/serengil/deepface/blob/master/deepface/detectors/Yolo.py)
```
weight_path = f"{folder_utils.get_deepface_home()}{PATH}"
print(weight_path)
```

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1038

Thank you @Any-Winter-4079

**Comment by gbaufake** [comment]
@serengil can you release a new version of DeepaFace on Pypi?

**Comment by serengil** [comment]
I will do it soon, meanwhile you can use the source code as

```shell
$ git clone https://github.com/serengil/deepface.git
$ cd deepface
$ pip install -e .
```
