### ISSUE TITLE
Lack of verbosity during AttributeErrors

### ISSUE THREAD

**Issue by 0phoi5** [serengil/deepface#1029]
Hi,
Firstly, thank you for the great work. This code is working excellently for me 99% of the time.
Occasionally, I will come across an image that is unreadable, for whatever reason, and get an AttributeError. In the below example, it's down to "NoneType object has no attribute shape."
This Issue has been raised specifically for verbosity purposes. Could we please have the image name added to the output when an error is thrown? At the moment, I am having to manually try and trace down what image(s) have a problem, when it really aught to be in the output.
Thank you for your time.

```
Finding representations:  42%|████████████████████████████████▉                                             | 420/993 [12:42<17:20,  1.82s/it]
Traceback (most recent call last):
  File "/home/ophois/.local/bin/deepface", line 8, in <module>
    sys.exit(cli())
  File "/home/ophois/.local/lib/python3.10/site-packages/deepface/DeepFace.py", line 390, in cli
    fire.Fire()
  File "/home/ophois/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ophois/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ophois/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ophois/.local/lib/python3.10/site-packages/deepface/DeepFace.py", line 229, in find
    return recognition.find(
  File "/home/ophois/.local/lib/python3.10/site-packages/deepface/modules/recognition.py", line 167, in find
    representations = __find_bulk_embeddings(
  File "/home/ophois/.local/lib/python3.10/site-packages/deepface/modules/recognition.py", line 326, in __find_bulk_embeddings
    img_objs = functions.extract_faces(
  File "/home/ophois/.local/lib/python3.10/site-packages/deepface/commons/functions.py", line 173, in extract_faces
    img_region = [0, 0, img.shape[1], img.shape[0]]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by 0phoi5** [comment]
The relevant section of code that needs amendment is;
```python
# img might be path, base64 or numpy array. Convert it to numpy whatever it is.
    img, img_name = load_image(img)
    img_region = [0, 0, img.shape[1], img.shape[0]]

    if detector_backend == "skip":
        face_objs = [(img, img_region, 0)]
    else:
        face_objs = DetectorWrapper.detect_faces(detector_backend, img, align)
```
If I get a chance to take a look myself, I will do so.

**Comment by 0phoi5** [comment]
Possibly not the perfect solution, but this works well enough.
{img_name} needs to be printed at the point of failure. I used a try/except, one can then see what image failed to read correctly and simply remove it from the input directory or fix the image itself.

```python
    # img might be path, base64 or numpy array. Convert it to numpy whatever it is.
    try:
        img, img_name = load_image(img)
        img_region = [0, 0, img.shape[1], img.shape[0]]

        if detector_backend == "skip":
            face_objs = [(img, img_region, 0)]
        else:
            face_objs = DetectorWrapper.detect_faces(detector_backend, img, align)
    except AttributeError as e:
        raise ValueError(f"Unreadable file - AttributeError occured for {img_name}: {e}")
``` 

```
ValueError: Unreadable file - AttributeError occured for /path/to/dir/failed_image.jpg: 'NoneType' object has no attribute 'shape'
```

**Comment by serengil** [comment]
Definitely, users should see a meaningful exception message.

Firstly, as I see you are using an old version of DeepFace. Would you please update the package first? This may not be an issue for the current package.

Instead of using try catch, I prefer to raise an error if img is None after load_image performed: https://github.com/serengil/deepface/blob/master/deepface/modules/detection.py#L77

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/1038
