### ISSUE TITLE
error generated on find function call

### ISSUE THREAD

**Issue by Devhercule** [serengil/deepface#1070]
Hello,

I'd like to find a face in an image database. This face is detected on one of the images in the database using the DeepFace.extract_faces() function (I've saved it). 
To do this, I used the DeepFace.find() function and it generated an error.

Here is my script :

```
import cv2
import os
from deepface import DeepFace

img_path = "C:\\Users\\me\\Documents\\deepface\\photos\\1.jpg"

img = cv2.imread(img_path)

face_objs = DeepFace.extract_faces(
    img_path=img_path, 
    target_size=(224, 224), 
    detector_backend='retinaface'
)

output_folder = "C:\\Users\\me\\Documents\\deepface\\faces"
os.makedirs(output_folder, exist_ok=True)

for i, face_obj in enumerate(face_objs):
    x, y, w, h = face_obj['facial_area']['x'], face_obj['facial_area']['y'], face_obj['facial_area']['w'], face_obj['facial_area']['h']
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    face_img_path = os.path.join(output_folder, f"face_{i+1}.jpg")
    face_img = img[y:y+h, x:x+w]
    cv2.imwrite(face_img_path, face_img)
    
dfs = DeepFace.find(img_path="C:\\Users\\me\\Documents\\deepface\\faces\\face_5.jpg", db_path="C:\\Users\\me\\Documents\\deepface\\photos")
```
and the error was :

```
C:\Users\me\Documents\deepface>py tmp.py.txt
2024-03-08 15:59:26.240677: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2024-03-08 15:59:30.159645: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\me\Documents\deepface\script.py.txt", line 32, in <module>
    dfs = DeepFace.find(img_path="C:\\Users\\me\\Documents\\deepface\\faces\\face_5.jpg", db_path="C:\\Users\\me\\Documents\\script\\photos")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\DeepFace.py", line 294, in find
    return recognition.find(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\modules\recognition.py", line 185, in find
    source_objs = detection.extract_faces(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepface\modules\detection.py", line 99, in extract_faces
    raise ValueError(
ValueError: Face could not be detected in C:\Users\me\Documents\deepface\faces\face_5.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

```

any idea ?

**Comment by serengil** [comment]
exception message is clear

`Face could not be detected in C:\Users\me\Documents\deepface\faces\face_5.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.`

**Comment by Devhercule** [comment]
I set enforce_detection param to False and it worked.
what's this param for, I can't find it anywhere in the documentation

**Comment by serengil** [comment]
it is explained in the docsting: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py#L255

if a face cannot be detected in the given image, library throws an exception by default.

if you set that arg to False, then library is attempting to run facial recognition with the image itself without detection. This decreases the model accuracy.

**Comment by Devhercule** [comment]
Thank you very much for your help !

Is there any way to avoid reducing the accuracy of the model?
