### ISSUE TITLE
v0.0.86 Docker broken

### ISSUE THREAD

**Issue by lounging-lizard** [serengil/deepface#1092]
### Description

Trying to bring up the docker container fails with the following log:

```
[2024-03-11 01:10:20 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2024-03-11 01:10:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-03-11 01:10:20 +0000] [1] [INFO] Using worker: sync
[2024-03-11 01:10:20 +0000] [8] [INFO] Booting worker with pid: 8
[2024-03-11 01:10:20 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/deepface/api/src/app.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)
[2024-03-11 01:10:20 +0000] [8] [INFO] Worker exiting (pid: 8)
[2024-03-11 01:10:20 +0000] [1] [INFO] Shutting down: Master
[2024-03-11 01:10:20 +0000] [1] [INFO] Reason: Worker failed to boot.
 ```

#### Steps to Reproduce
1. Pull repo

2. Build the image
`docker build -t deepface -f Dockerfile .`

3. Run the image
`docker run deepface`

### Expected Behavior

The Docker container builds and subsequently runs successfully.

**Comment by lounging-lizard** [comment]
@serengil it appears the issue is a result of https://github.com/serengil/deepface/commit/1f771565a23d116bfd4f86c661cc0c5a06f19ed6

If I build from the docker container builds and runs fine

**Comment by serengil** [comment]
Recently, many issues have been raised about the imcompatible versions of dependencies. So, i want to provide a working docker image anytime. My bad, did not test 😅

Just updated the local requirements: https://github.com/serengil/deepface/commit/65d6312c978d310598083d6efbc3ef8b5fe29313

If you pull the source code again, it should work now

**Comment by lounging-lizard** [comment]
Thank you @serengil I would have opened a PR myself but am not very familiar with this project or python

**Comment by serengil** [comment]
@lounging-lizard no problem at all, i broken it, sorting is my responsibility 😁
