### ISSUE TITLE
ValueError: The layer sequential_1 has never been called and thus has no defined input.

### ISSUE THREAD

**Issue by zoyahammad** [serengil/deepface#1131]
I am running a simple script within my Anaconda virtual env

```
from deepface import DeepFace

face_analysis = DeepFace.analyze("face.jpg")
print(face_analysis)
```
But I keep getting this error.
```
Action: age:  25%|██████████████████████████▊                                                                                | 1/4 [00:02<00:06,  2.08s/it]
Traceback (most recent call last):
  File "C:\Users\Ctrend.pk\Cheer-Check\test2.py", line 9, in <module>
    analysis = DeepFace.analyze(img_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\deepface\DeepFace.py", line 222, in analyze
    return demography.analyze(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\deepface\modules\demography.py", line 157, in analyze
    apparent_age = modeling.build_model("Age").predict(img_content)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\deepface\modules\modeling.py", line 57, in build_model
    model_obj[model_name] = model()
                            ^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\deepface\extendedmodels\Age.py", line 32, in __init__
    self.model = load_model()
                 ^^^^^^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\deepface\extendedmodels\Age.py", line 61, in load_model
    age_model = Model(inputs=model.input, outputs=base_model_output)
                             ^^^^^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\ops\operation.py", line 228, in input
    return self._get_node_attribute_at_index(0, "input_tensors", "input")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\ops\operation.py", line 259, in _get_node_attribute_at_index
    raise ValueError(
ValueError: The layer sequential_1 has never been called and thus has no defined input.
```

Deepface version: 0.0.87

tensorflow
Version: 2.16.1

I think it fetches the age but then doesn't proceed. What am I missing out on?

**Comment by serengil** [comment]
Sorted in 0.0.88

https://github.com/serengil/deepface/releases/tag/v0.0.88

**Comment by zoyahammad** [comment]
Did I need to uninstall & reinstall both tensorflow/deepface in order for this to run? Because without it, it still didn't. Also is there a recommended Python version as well? It didn't work for me on Python 3.12

**Comment by serengil** [comment]
Just upgrade deepface

**Comment by zoyahammad** [comment]
FYI:

Deepface 0.0.88
tesnorflow 2.16.1
python 3.12.2

Still gives the following error:

`[ImportError: cannot import name 'LocallyConnected2D' from 'tensorflow.keras.layers'](https://stackoverflow.com/questions/78131429/importerror-cannot-import-name-locallyconnected2d-from-tensorflow-keras-laye)`

**Comment by serengil** [comment]
i will publish a new release - give me some time

**Comment by serengil** [comment]
Upgrade to 0.0.89 please

**Comment by zoyahammad** [comment]
First, it asked me to download tf-keras but then this:

`  File "C:\Users\Ctrend.pk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by serengil** [comment]
@zoyahammad most probably you are getting this because of proxy or firewall
