### ISSUE TITLE
Unable to synchronously open object (bad symbol table node signature)

### ISSUE THREAD

**Issue by fffeergrrrrtrrt** [serengil/deepface#1153]
hello me run frist code and this error show by module

> python deep.py
2024-03-29 06:18:27.242071: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-29 06:18:29.071792: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-03-29 06:18:32.699612: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 411041792 exceeds 10% of free system memory.
2024-03-29 06:18:32.966953: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 411041792 exceeds 10% of free system memory.
2024-03-29 06:18:33.115372: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 411041792 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "/home/qqqq/Documents/py/face/deepface/deep.py", line 5, in <module>
    result = DeepFace.verify(img1_path = "katrinforg.jpg", img2_path = "katrintest2.jpg")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qqqq/.deepface/weights/deepface/deepface/DeepFace.py", line 133, in verify
    return verification.verify(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/qqqq/.deepface/weights/deepface/deepface/modules/verification.py", line 93, in verify
    model: FacialRecognition = modeling.build_model(model_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qqqq/.deepface/weights/deepface/deepface/modules/modeling.py", line 57, in build_model
    model_obj[model_name] = model()
                            ^^^^^^^
  File "/home/qqqq/.deepface/weights/deepface/deepface/basemodels/VGGFace.py", line 45, in __init__
    self.model = load_model()
                 ^^^^^^^^^^^^
  File "/home/qqqq/.deepface/weights/deepface/deepface/basemodels/VGGFace.py", line 139, in load_model
    model.load_weights(output)
  File "/home/qqqq/.local/lib/python3.11/site-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/qqqq/.local/lib/python3.11/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (bad symbol table node signature)'

**Comment by serengil** [comment]
Seems you have a problem in your tensorflow installation.

**Comment by fffeergrrrrtrrt** [comment]
code::
> cat deep.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from deepface import DeepFace
result = DeepFace.verify(img1_path = "katrinforg.jpg", img2_path = "katrintest2.jpg")

**Comment by fffeergrrrrtrrt** [comment]
like this problem opened in by facenet-pytourch but people answer me to error in pakge

**Comment by fffeergrrrrtrrt** [comment]
me reinstall tensoflow and agian use deep face I will send the result and thank you for your response

**Comment by serengil** [comment]
I also suspect the broken weights file. Please try to delete files under ~/.deepface/weights

**Comment by fffeergrrrrtrrt** [comment]
ooh , me remove  ~/.deepface/weights and will send the result
