### ISSUE TITLE
ValueError: Exception while processing img1_path

### ISSUE THREAD

**Issue by xjDUAN184** [serengil/deepface#1255]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.92

### Python version

3.8

### Dependencies

Package                      Version     Editable project location
---------------------------- ----------- ----------------------------------
absl-py                      2.1.0
asttokens                    2.0.5
astunparse                   1.6.3
backcall                     0.2.0
beautifulsoup4               4.12.3
blinker                      1.8.2
cachetools                   5.3.3
certifi                      2024.6.2
charset-normalizer           3.3.2
click                        8.1.7
comm                         0.2.1
debugpy                      1.6.7
decorator                    5.1.1
deepface                     0.0.92      /nfs1/56dev/root/dxj/jike/deepface
executing                    0.8.3
filelock                     3.14.0
fire                         0.6.0
Flask                        3.0.3
flatbuffers                  24.3.25
gast                         0.4.0
gdown                        5.2.0
google-auth                  2.30.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.64.1
gunicorn                     22.0.0
h5py                         3.11.0
idna                         3.7
importlib-metadata           7.0.1
ipykernel                    6.28.0
ipython                      8.12.2
itsdangerous                 2.2.0
jedi                         0.18.1
Jinja2                       3.1.4
jupyter_client               8.6.0
jupyter_core                 5.5.0
keras                        2.13.1
libclang                     18.1.1
Markdown                     3.6
MarkupSafe                   2.1.5
matplotlib-inline            0.1.6
mtcnn                        0.1.1
nest-asyncio                 1.6.0
numpy                        1.24.3
oauthlib                     3.2.2
opencv-python                4.10.0.82
opt-einsum                   3.3.0
packaging                    23.2
pandas                       2.0.3
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
pillow                       10.3.0
pip                          24.0
platformdirs                 3.10.0
prompt-toolkit               3.0.43
protobuf                     4.25.3
psutil                       5.9.0
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyasn1                       0.6.0
pyasn1_modules               0.4.0
Pygments                     2.15.1
PySocks                      1.7.1
python-dateutil              2.9.0.post0
pytz                         2024.1
pyzmq                        25.1.2
requests                     2.32.3
requests-oauthlib            2.0.0
retina-face                  0.0.17
rsa                          4.9
setuptools                   69.5.1
six                          1.16.0
soupsieve                    2.5
stack-data                   0.2.0
tensorboard                  2.13.0
tensorboard-data-server      0.7.2
tensorflow                   2.13.1
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.34.0
termcolor                    2.4.0
tornado                      6.3.3
tqdm                         4.66.4
traitlets                    5.7.1
typing_extensions            4.5.0
tzdata                       2024.1
urllib3                      2.2.1
wcwidth                      0.2.5
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0
zipp                         3.17.0

### Reproducible example

```Python
result = DeepFace.verify(
  model_name = "Facenet512",
  img1_path = "/nfs1/56dev/root/dxj/jike/data/tom/tom_3.jpg",
  img2_path = "/nfs1/56dev/root/dxj/jike/data/tom/tom_5.jpg",
)
```

### Relevant Log Output

(face_test) (base) root@bigdata-gpu01:/nfs1/56dev/root/dxj# /root/anaconda3/envs/face_test/bin/python /nfs1/56dev/root/dxj/jike/test.py
2024-06-11 04:15:42.308968: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-11 04:15:44.082942: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-06-11 04:15:48.289210: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2024-06-11 04:15:48.289269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 18011 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:03:00.0, compute capability: 8.6
2024-06-11 04:15:48.289831: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2024-06-11 04:15:48.289882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 21883 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:04:00.0, compute capability: 8.6
2024-06-11 04:15:49.511652: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 411041792 exceeds 10% of free system memory.
2024-06-11 04:15:50.053616: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 67108864 exceeds 10% of free system memory.
2024-06-11 04:15:50.167234: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 42958848 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "/nfs1/56dev/root/dxj/jike/deepface/deepface/modules/verification.py", line 130, in verify
    img1_embeddings, img1_facial_areas = __extract_faces_and_embeddings(
  File "/nfs1/56dev/root/dxj/jike/deepface/deepface/modules/verification.py", line 239, in __extract_faces_and_embeddings
    img_objs = detection.extract_faces(
  File "/nfs1/56dev/root/dxj/jike/deepface/deepface/modules/detection.py", line 96, in extract_faces
    raise ValueError(
ValueError: Face could not be detected in /nfs1/56dev/root/dxj/jike/data/tom/tom_0.jpg.Please confirm that the picture is a face photo or consider to set enforce_detection param to False.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs1/56dev/root/dxj/jike/test.py", line 4, in <module>
    result = DeepFace.verify(
  File "/nfs1/56dev/root/dxj/jike/deepface/deepface/DeepFace.py", line 144, in verify
    return verification.verify(
  File "/nfs1/56dev/root/dxj/jike/deepface/deepface/modules/verification.py", line 141, in verify
    raise ValueError("Exception while processing img1_path") from err
ValueError: Exception while processing img1_path

### Expected Result

in verification.py, line 239 ~247
    img_objs = detection.extract_faces(
        img_path=img_path,
        detector_backend=detector_backend,
        grayscale=False,
        enforce_detection=enforce_detection,
        align=align,
        expand_percentage=expand_percentage,
        anti_spoofing=anti_spoofing,
    )

in process of  debug, find the variable img_objs = [].   my pictures is :
![image](https://github.com/serengil/deepface/assets/73686733/53b88d81-e6a5-4feb-b936-bc8183baf201)
![image](https://github.com/serengil/deepface/assets/73686733/3d34ccb5-08a3-4c19-a889-430fe155691b)
How to solve it?

### What happened instead?

get correct verity result

### Additional Info

I have used vgg, facenet512

**Comment by serengil** [comment]
Exception message is clear, this is not a bug.
