### ISSUE TITLE
Running into this error while running Ensemble model on MacOS 

### ISSUE THREAD

**Issue by iamrishab** [serengil/deepface#130]
Had anyone faced similar issue on MacOS?

**Traceback**
```
Ensemble learning enabled
Traceback (most recent call last):
  File "test_deepface.py", line 48, in <module>
    resp_obj = DeepFace.verify(img1, img2, model_name = "Ensemble")
  File "/Users/b0220428/venvs/deepface/lib/python3.6/site-packages/deepface/DeepFace.py", line 41, in verify
    import lightgbm as lgb #lightgbm==2.3.1
  File "/Users/b0220428/venvs/deepface/lib/python3.6/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset
  File "/Users/b0220428/venvs/deepface/lib/python3.6/site-packages/lightgbm/basic.py", line 43, in <module>
    _LIB = _load_lib()
  File "/Users/b0220428/venvs/deepface/lib/python3.6/site-packages/lightgbm/basic.py", line 34, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/b0220428/.pyenv/versions/3.6.8/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/Users/b0220428/.pyenv/versions/3.6.8/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/b0220428/venvs/deepface/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/b0220428/venvs/deepface/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
```

Thanks in advance!

**Comment by iamrishab** [comment]
Fixed.
https://github.com/microsoft/LightGBM/issues/1369#issuecomment-504619338
