### ISSUE TITLE
[BUG]: Incompatibility with TensorFlow 2.14 / Keras 2.14

### ISSUE THREAD

**Issue by vertify-mldev1** [serengil/deepface#1354]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

0.0.93

### Python version

3.11.0

### Operating System

Ubuntu 18.04.6 LTS

### Dependencies

```
absl-py==2.1.0
albumentations==1.4.3
anyio==4.6.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
astunparse==1.6.3
async-lru==2.0.4
attrs==24.2.0
babel==2.16.0
beautifulsoup4==4.12.3
bleach==6.1.0
blinker==1.8.2
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
comm==0.2.2
contourpy==1.3.0
cycler==0.12.1
debugpy==1.8.6
decorator==4.4.2
deepface==0.0.93
defusedxml==0.7.1
dm-tree==0.1.8
executing==2.1.0
fastjsonschema==2.20.0
filelock==3.16.1
fire==0.6.0
Flask==3.0.3
Flask-Cors==5.0.0
flatbuffers==24.3.25
fonttools==4.54.1
fqdn==1.5.1
gast==0.6.0
gdown==5.2.0
google-auth==2.35.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.66.2
gunicorn==23.0.0
h11==0.14.0
h5py==3.12.1
httpcore==1.0.5
httpx==0.27.2
idna==3.10
imageio==2.35.1
imageio-ffmpeg==0.4.9
ipykernel==6.29.5
ipython==8.27.0
ipywidgets==8.1.5
isoduration==20.11.0
itsdangerous==2.2.0
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13
keras==2.14.0
kiwisolver==1.4.7
lazy_loader==0.4
libclang==18.1.1
Markdown==3.7
MarkupSafe==2.1.5
matplotlib==3.9.2
matplotlib-inline==0.1.7
mistune==3.0.2
ml-dtypes==0.2.0
moviepy==1.0.3
mtcnn==0.1.1
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.3
notebook_shim==0.2.4
numpy==1.26.4
oauthlib==3.2.2
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
opt_einsum==3.4.0
overrides==7.7.0
packaging==24.1
pandas==2.2.3
pandocfilters==1.5.1
parso==0.8.4
patsy==0.5.6
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.3.6
proglog==0.1.10
prometheus_client==0.21.0
prompt_toolkit==3.0.48
protobuf==4.25.5
psutil==6.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
pydantic==1.8.2
Pygments==2.18.0
pyparsing==3.1.4
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
remodnav==1.1.1
requests==2.32.3
requests-oauthlib==2.0.0
retina-face==0.0.17
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.20.0
rsa==4.9
scikit-image==0.24.0
scikit-learn==1.5.2
scipy==1.14.1
Send2Trash==1.8.3
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
statsmodels==0.14.3
tensorboard==2.14.1
tensorboard-data-server==0.7.2
tensorflow==2.14.1
tensorflow-addons==0.23.0
tensorflow-estimator==2.14.0
tensorflow-io-gcs-filesystem==0.37.1
tensorflow-probability==0.22.1
termcolor==2.4.0
terminado==0.18.1
threadpoolctl==3.5.0
tifffile==2024.9.20
tinycss2==1.3.0
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
typeguard==2.13.3
types-python-dateutil==2.9.0.20240906
typing_extensions==4.12.2
tzdata==2024.2
uri-template==1.3.0
urllib3==2.2.3
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.0.4
widgetsnbextension==4.0.13
wrapt==1.14.1
```

### Reproducible example

```Python
DeepFace.extract_faces(
    img_path=np.ones((300,300,3)), # any numpy image
    enforce_detection=True,
    detector_backend='retinaface',
)
```

### Relevant Log Output

```
Traceback (most recent call last):

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)
          ^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/<user>/Documents/Python/Python Packages/vgu/vgu/prediction/facedetection.py", line 264, in analyze
    lbl_dicts = DeepFace.extract_faces(
                ^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/deepface/DeepFace.py", line 549, in extract_faces
    return detection.extract_faces(
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/deepface/modules/detection.py", line 95, in extract_faces
    face_objs = detect_faces(
                ^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/deepface/modules/detection.py", line 206, in detect_faces
    face_detector: Detector = modeling.build_model(
                              ^^^^^^^^^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/deepface/modules/modeling.py", line 96, in build_model
    cached_models[task][model_name] = model()
                                      ^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/deepface/models/face_detection/RetinaFace.py", line 9, in __init__
    self.model = rf.build_model()
                 ^^^^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/retinaface/RetinaFace.py", line 54, in build_model
    retinaface_model.build_model(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/retinaface/model/retinaface_model.py", line 1218, in build_model
    face_rpn_cls_score_reshape_stride32 = tf.transpose(
                                          ^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 72, in error_handler
    del filtered_tb

  File "/home/<user>/.pyenv/versions/Python_3.11/lib/python3.11/site-packages/keras/src/utils/layer_utils.py", line 966, in split_out_first_arg
    elif self._arg_names[0] in kwargs:
         ~~~~~~~~~~~~~~~^^^

IndexError: list index out of range
```

**Comment by serengil** [comment]
Seems a tf error instead of deepface itself

**Comment by vertify-mldev1** [comment]
Alright, then i will stay on tf 2.9.3 for now. Thanks for the reply!

**Comment by almirb** [comment]
> Alright, then i will stay on tf 2.9.3 for now. Thanks for the reply!

Hello @vertify-mldev1 !
Is that the latest version of tf that works well with deepface?

Thanks!

**Comment by vertify-mldev1** [comment]
Hi @almirb , I did not try any other versions.

**Comment by TheArKaID** [comment]
*Just drop a note, I use 2.15.0 and it works.
