### ISSUE TITLE
Api error with new updated version of deepface and repo

### ISSUE THREAD

**Issue by t3ch9** [serengil/deepface#147]
Getting the following error when running api.py

Traceback (most recent call last):
  File "api.py", line 90, in <module>
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by t3ch9** [comment]
When I replace line 90 graph = tf.get_default_graph() with graph = tf.compat.v1.get_default_graph() the api.py runs but when I call is made with the provided the file deepface.postman_collection.json via Postman, getting the following:

From Postman:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
	there is an error in the application.</p>

From shell:

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Input request of  579154f4-1054-4ea5-9ca5-3e10c84af8e5  has  3  pairs to verify
Verification:   0%|                                                                              | 0/3 [00:00<?, ?it/s]WARNING:tensorflow:From C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\tensorflow\python\keras\engine\training_v1.py:2070: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Verification:   0%|                                                                              | 0/3 [00:00<?, ?it/s]
[2020-12-14 02:09:42,016] ERROR in app: Exception on /verify [POST]
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 199, in verify
    resp_obj = DeepFace.verify(instances, model_name = model_name, distance_metric = distance_metric, model = vggface_model)
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\deepface\DeepFace.py", line 162, in verify
    img1_representation = custom_model.predict(img1)[0,:]
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 978, in predict
    self._assert_built_as_v1()
  File "C:\Users\admin\miniconda3\envs\deepface2\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 829, in _assert_built_as_v1
    'Your Layer or Model is in an invalid state. This can happen if you '
ValueError: Your Layer or Model is in an invalid state. This can happen if you are interleaving estimator/non-estimator models or interleaving models/layers made in tf.compat.v1.Graph.as_default() with models/layers created outside of it. Converting a model to an estimator (via model_to_estimator) invalidates all models/layers made before the conversion (even if they were not the model converted to an estimator). Similarly, making a layer or a model inside a a tf.compat.v1.Graph invalidates all layers/models you previously made outside of the graph.
127.0.0.1 - - [14/Dec/2020 02:09:42] "[35m[1mPOST /verify HTTP/1.1[0m" 500 -

**Comment by serengil** [comment]
Oke, I fixed the problem. You can copy the latest version of api.py here: https://github.com/serengil/deepface/blob/master/api/api.py

To sum up, in tf 2 you should not create a graph and call functions inside of it. I check version control. Call verify and analyze functions directly for tf2, and call them in with graph term for tf1.
