### ISSUE TITLE
ValueError: Classification metrics can't handle a mix of unknown and binary targets

### ISSUE THREAD

**Issue by khawar512** [serengil/deepface#157]
Previously, it worked fine on Python 3.5 but now Python 3.5 is unavailable. So I have to install python 3.7 for better working.

**Code**
```
predictions = gbm.predict(x_test)
predictions_classes = []
for i in predictions:
    prediction_class = np.argmax(i)
    predictions_classes.append(prediction_class)

cm = confusion_matrix(y_test, predictions_classes)
print(cm)
```
**When i checked both y_test, predictions_classes matrix, it contains 0 and 1**

**Traceback**

```
Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 847, in <module>
    cm = confusion_matrix(y_test, predictions_classes, normalize=False)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 276, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 91, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of unknown and binary targets
```

**Comment by serengil** [comment]
could you please print y_test and predictions_classes?

**Comment by khawar512** [comment]
![133114669_1628964930640448_2931544844112209119_n](https://user-images.githubusercontent.com/11488932/103345346-816f2880-4ad4-11eb-8d6f-d87980344845.png)

**Comment by khawar512** [comment]
cm = confusion_matrix(y_true.round(), predictions_classes.round())
I implemented this one.


```
AttributeError: 'int' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 847, in <module>
    cm = confusion_matrix(y_test.round(), predictions_classes.round())
TypeError: loop of ufunc does not support argument 0 of type int which has no callable rint method


```

**Comment by serengil** [comment]
Could you please run the following lines. The second one stores commas whereas the first one does not. It seems they are different type of object.

```
print("y_true: (",type(y_true),")", y_true)
print("predictions_classes: (",type(predictions_classes),")", predictions_classes)
```

**Comment by khawar512** [comment]
Actually this is y_test instead of y_true

```
y_test: ( <class 'numpy.ndarray'> ) [1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 1
 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 1 1 0 1
 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0
 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0
 0 1 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0
 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0
 1 0 0 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 1 0 1 1
 1 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1
 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 0 0 1
 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0
 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1
 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 1
 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1 1 1 0 0
 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 0 1 0 0 1]
predictions_classes: ( <class 'list'> ) [0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1]
Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 850, in <module>
    cm = confusion_matrix(y_test, predictions_classes)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 276, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 91, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of unknown and binary targets
```

**Comment by serengil** [comment]
One is numpy array and the other is python list. That's the problem I think. Could you test the following commands?

`cm = confusion_matrix(y_test, np.array(predictions_classes))`

or 

`cm = confusion_matrix(list(y_test), predictions_classes)`

**Comment by khawar512** [comment]
```
**cm = confusion_matrix(y_test, np.array(predictions_classes))**

Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 850, in <module>
    cm = confusion_matrix(y_test, np.array(predictions_classes))
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 276, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 91, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of unknown and binary targets

```
**for Second one, i got an error when constructing roc curve**

```
Precision:  87.08133971291866 %
Recall:  71.09375 %
F1 score  78.27956989247312 %
Accuracy:  80.23483365949119 %

Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 889, in <module>
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 776, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 539, in _binary_clf_curve
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: unknown format is not supported
```

**Comment by khawar512** [comment]
I am also requesting you to please tell me the reason why i am getting this error? I have just change the images and image list.

**Comment by serengil** [comment]
The first problem is solved. Could you share the results for following lines:

```
print("y_true: (",type(y_test),")", y_test)
print("predictions_classes: (",type(y_pred_proba),")", y_pred_proba)
```

**Comment by khawar512** [comment]
y_pred_proba is our "predictions_classes". **Am i right?**

**Comment by khawar512** [comment]
print("Precision: ", 100 * precision, "%")
print("Recall: ", 100 * recall, "%")
print("F1 score ", 100 * f1, "%")
print("Accuracy: ", 100 * accuracy, "%")

print("y_test: (",type(y_test),")", y_test)
print("y_pred_proba: (",type(predictions_classes),")", predictions_classes)

```
Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 893, in <module>
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 776, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/khawar/anaconda3/envs/deepface/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 539, in _binary_clf_curve
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: unknown format is not supported
```

**Comment by serengil** [comment]
I could not see the results of those lines

```
print("y_test: (",type(y_test),")", y_test)
print("y_pred_proba: (",type(predictions_classes),")", predictions_classes)
```

y_pred_proba should store probabilities. I mean that it should be a value between [0, 1] and it should be continuous.

**Comment by serengil** [comment]
BTW, those are related to python core instead of deepface. That's why, I close this issue. If you have still questions, we can talk here.
