### ISSUE TITLE
ValueError: Wrong number of items passed 1, placement implies 2

### ISSUE THREAD

**Issue by khawar512** [serengil/deepface#159]
I figured out both error ROC curve and running big datasets through multiprocessing. This process works fine but after 30 mints, i suddenly get an error.

**Multiprocessing Code Changed:**

```
    for i in range(0, len(values) - 1):
        for j in range(i + 1, len(values)):
            # print(values[i], " and ", values[j])
            positive = []
            positive.append(values[i])
            positive.append(values[j])
            print(positive)
            proc = multiprocessing.Process(args=(positive,)) 
            print(proc)
            positives.append(proc)
            proc.start()

        for proc in positives:
            proc.join()

positives = pd.DataFrame(positives, columns=["file_x", "file_y"])
```
**Trace back** 
```
['1013_StephenHawking_67_m.jpg', '1023_StephenHawking_45_m.jpg']
<Process(Process-236167, initial)>
Traceback (most recent call last):
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1671, in create_block_manager_from_blocks
    make_block(values=blocks[0], placement=slice(0, len(axes[0])))
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2744, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2400, in __init__
    super().__init__(values, ndim=ndim, placement=placement)
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 131, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 1, placement implies 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khawar/deepface/tests/Ensemble-Face-Recognition.py", line 53, in <module>
    positives = pd.DataFrame(positives, columns=["file_x", "file_y"])
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 523, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 234, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/home/khawar/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1681, in create_block_manager_from_blocks
    raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
ValueError: Shape of passed values is (236167, 1), indices imply (236167, 2)

```

**Comment by serengil** [comment]
This is directly related to python core. I could not understand the relation with deepface?
