### ISSUE TITLE
How to calculate candidate score in % in elastic search

### ISSUE THREAD

**Issue by rockstarvibu** [serengil/deepface#167]
I'm using same code as you did in Elasticsearch. Im also using euclidean distance in query. I want to get score in % so I multiplied candidate_score * 100 but still results are always coming between 6%  to 12%. can you tell me the process to get candidate score between 0 to 100%..

Thanks

**Comment by serengil** [comment]
did you use facenet or dlib?

**Comment by rockstarvibu** [comment]
im using facenet

**Comment by serengil** [comment]
could you test with dlib please as well?

**Comment by rockstarvibu** [comment]
okay but i want to use facenet because it has good accuracy of 99.63%.. 

basically i want confidence score from 0 to 100%

**Comment by rockstarvibu** [comment]
Error occurs
`ModuleNotFoundError: No module named 'dlib'`
I Tried 
`!pip install dlib` but again error
`
  ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/setup.py'"'"'; __file__='"'"'/private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-record-kobehd0u/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.8/dlib
         cwd: /private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/
    Complete output (55 lines):
    running install
    running build
    running build_py
    package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "/private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/opt/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/opt/anaconda3/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/opt/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/opt/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/setup.py", line 223, in <module>
        setup(
      File "/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/private/var/folders/6g/zt2sx56j5r32k8pzbk8c468r0000gn/T/pip-install-19y483uu/dlib_9f5cd7998e0b4ae1b3a594cc672a7d88/setup.py", line 122, in get_cmake_version
        raise RuntimeError("\n*******************************************************************\n" +
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: _dlib_pybind11
`

**Comment by serengil** [comment]
Those are the max threshold values for facenet

`'Facenet':  {'cosine': 0.40, 'euclidean': 10, 'euclidean_l2': 0.80}`

You can find the found distance and max threshold value first. If it is equal to 0.40 (distance would be 0 and max threshold is 0.40), then it has a 100% confidence score. If it is equal to 0, then it has a 99.63% confidence score. You can normalize the confidence based on this approach.

**Comment by rockstarvibu** [comment]
but its not possible in large scale face recognition...

**Comment by serengil** [comment]
why? elasticsearch returns you the distance value.

**Comment by rockstarvibu** [comment]
elasticsearch is returning only max_score: 0.0901235 and with score of single image also

**Comment by rockstarvibu** [comment]
can you help me to calculate distance between these result?

**Comment by serengil** [comment]
0.0901235 -> this is the distance actually. When it closes to 0 then, confidence closes to 100%.

**Comment by rockstarvibu** [comment]
can you tell me how to convert it in %? should I have to multiply score * 100 or something else.

**Comment by serengil** [comment]
try this: 100 - max_score

**Comment by rockstarvibu** [comment]
by using this 100 - max_score. confidence should be decrease as we go below.. but with this confidence is increasing as we move down below which is incorrect...

**Comment by rockstarvibu** [comment]
100 - max_score. is not providing accurate results

**Comment by rockstarvibu** [comment]
i tried alot but not able to find %. can you plz help me in this...

Thanks

**Comment by serengil** [comment]
unfortunately, there is no linear formula to find the confidence. I recommend you to use ensembe (set model_name to Ensemble). It returns a score. That might help you.
