### ISSUE TITLE
Keras requires TensorFlow2.2 or higher, but when I update tensorflow to 2.2 it still doesnt work

### ISSUE THREAD

**Issue by Zicheeee** [serengil/deepface#179]
(cv) pi@raspberrypi:~/Face Recognition/DeepFace $ python faceReader.py
2021-01-29 22:27:45.551803: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "faceReader.py", line 1, in <module>
    from deepface import DeepFace
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/deepface/DeepFace.py", line 1, in <module>
    from keras.preprocessing import image
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by serengil** [comment]
it seems that you cannot install tensorflow correctly. you might open this issue on tensorflow repo. 

you might try to install dependencies respectively without its dependencies.

```
pip install tensorflow --no-deps
pip install keras --no-deps
pip install deepface --no-deps
```
