### ISSUE TITLE
ValueError: could not convert string to float: 'deepface/tests/dataset/032A13.JPG'

### ISSUE THREAD

**Issue by khawar512** [serengil/deepface#184]
I am getting an error in this line I don't know what is the exact reason?

 ```
params = {
        'task': 'train'
        , 'boosting_type': 'gbdt'
        , 'objective': 'multiclass'
        , 'num_class': 2
        , 'metric': 'multi_logloss'
    }

    gbm = lgb.train(params, lgb_train, num_boost_round=1000, early_stopping_rounds=15, valid_sets=lgb_test)
    gbm.save_model("face-recognition-ensemble-model.txt")
```

**Traceback**

```
Traceback (most recent call last):
  File "/home/khawar/.local/lib/python3.6/site-packages/lightgbm/engine.py", line 231, in train
    booster = Booster(params=params, train_set=train_set)
  File "/home/khawar/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 2053, in __init__
    train_set.construct()
  File "/home/khawar/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 1325, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/home/khawar/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 1123, in _lazy_init
    self.__init_from_np2d(data, params_str, ref_dataset)
  File "/home/khawar/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 1162, in __init_from_np2d
    data = np.array(mat.reshape(mat.size), dtype=np.float32)
ValueError: could not convert string to float: 'deepface/tests/dataset/032A13.JPG'
```

**Comment by serengil** [comment]
It seems the content of lgb_train, lgb_test causes this error. That's all related to your lightgbm model. It is out of scope of deepface, right?

**Comment by khawar512** [comment]
This is related with your ensemble.py file located in tests folder.

**Comment by serengil** [comment]
As I mentioned before, you might have a string column in lgb_train or lgb_test.

However, this is not seen here: https://github.com/serengil/deepface/blob/master/tests/Ensemble-Face-Recognition.py

**Comment by khawar512** [comment]
could please tell me the origin of this problem? Then, I will be debug it because now I am matching all code line by line

**Comment by khawar512** [comment]
problem solved
