### ISSUE TITLE
DeepFace.find error

### ISSUE THREAD

**Issue by saosophea9988** [serengil/deepface#218]
I use deepface version 0.0.50
I just follow instruction, but it show error, but if use `model=DeepFace.build_model('VGG-Face')` in df = `DeepFace.find(img_path="example.jpg", db_path="multiple", model=DeepFace.build_model('VGG-Face'),model_name="Facenet", enforce_detection=True)` it work fine but if I change to the same name of model="Facenet" or other model name it gonna show the same error (`model=DeepFace.build_model('Facenet')`).
error show **128** is different from **2622**)

this is my code:
df = DeepFace.find(img_path="example.jpg", db_path="multiple", model_name="Facenet", enforce_detection=True)

```
Traceback (most recent call last):
  File "/Users/sophea/Desktop/deepface-master/Main/main.py", line 8, in <module>
    df = DeepFace.find(img_path="example.jpg, db_path="multiple", model_name="Facenet", enforce_detection=True)
  File "/Users/sophea/Desktop/deepface-master/deepface/DeepFace.py", line 621, in find
    distance = dst.findCosineDistance(source_representation, target_representation)
  File "/Users/sophea/Desktop/deepface-master/deepface/commons/distance.py", line 4, in findCosineDistance
    a = np.matmul(np.transpose(source_representation), test_representation)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 128 is different from 2622)
```

**Comment by serengil** [comment]
Hello,

model_name must be same with the input of build_model function.

```
model_name = 'Facenet'
model = DeepFace.build_model(model_name)
print(model_name," built")

obj = DeepFace.find(img_path="deepface/tests/dataset/img1.jpg"
    , db_path="deepface/tests/dataset"
    , model = model
    , model_name = model_name
    , enforce_detection=True
)

print(obj)
```

Is there any warning as shown below? You should delete the pkl to solve the issue.

```
WARNING: Representations for images in  deepface/tests/dataset  folder were previously stored in  representations_facenet.pkl . If you added new instances after this file creation, then please delete this file and call find function again. It will create it again.
There are  60  representations found in  representations_facenet.pkl
```

**Comment by saosophea9988** [comment]
Thank you very much, it solve, bc I didn't delete pkl file.
