### ISSUE TITLE
Issue with using deepface with flask in server

### ISSUE THREAD

**Issue by slpraveenath** [serengil/deepface#42]
_I am getting the following issue with my flask app when I am running it from the server.It works only for the first time after reloading the flask app. But It works fine all the time in my local machine. _

Actions to do:  ['age', 'gender']
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1075, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3613, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3692, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Placeholder:0", shape=(3, 3, 3, 64), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/isl_gpu_desktop/Documents/project/PeopleCountWithAgeGender/app.py", line 88, in gen
    frame = people_counter_obj.run()
  File "/home/isl_gpu_desktop/Documents/project/PeopleCountWithAgeGender/people_counter.py", line 416, in run
    self.detect_faces(frame)
  File "/home/isl_gpu_desktop/Documents/project/PeopleCountWithAgeGender/people_counter.py", line 373, in detect_faces
    results = DeepFace.analyze(face_img, ['age', 'gender'])
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/deepface/DeepFace.py", line 192, in analyze
    age_model = Age.loadModel()
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/deepface/extendedmodels/Age.py", line 40, in loadModel
    age_model.load_weights(home+'/.deepface/weights/age_model_weights.h5')
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/keras/engine/network.py", line 1180, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/keras/engine/saving.py", line 929, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2435, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/isl_gpu_desktop/peopleCount/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1078, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(3, 3, 3, 64), dtype=float32) is not an element of this graph.

**Comment by serengil** [comment]
please confirm that you are running the api for the following environment

tensorflow==1.9.0
keras==2.2.0

**Comment by slpraveenath** [comment]
Yes, I am using the same versions of tensorflow and keras.

**Comment by mviennas** [comment]
i have the same problem. By default if you have a clean environment (only python 3.6) and you run the following command "pip install deepface" you will get tensorflow 2.2

I manage to overcome this issue using the following commands (install tensorflow==1.9.0
keras==2.2.0):
pip install --no-cache-dir -r requirements.txt
pip install deepface

[requirements.txt](https://github.com/serengil/deepface/files/4771235/requirements.txt)

**Comment by serengil** [comment]
@mviennas thank you for the solution. I'm going to update setup.py and requirements.txt.
