### ISSUE TITLE
race parameter of Deepface.analyze function doesn't work. 

### ISSUE THREAD

**Issue by timurturbil** [serengil/deepface#443]
race parameter doesn't work, Here is what does it return; 
```
Traceback (most recent call last):
  File "C:\Users\timur\Desktop\basic\python\age-predictor\main.py", line 8, in <module>
    obj = DeepFace.analyze(img_path = img)
  File "C:\Users\timur\AppData\Roaming\Python\Python310\site-packages\deepface\DeepFace.py", line 358, 
in analyze
    models['race'] = build_model('Race')
  File "C:\Users\timur\AppData\Roaming\Python\Python310\site-packages\deepface\DeepFace.py", line 61, in build_model
    model = model()
  File "C:\Users\timur\AppData\Roaming\Python\Python310\site-packages\deepface\extendedmodels\Race.py", line 61, in loadModel
    race_model.load_weights(home+'/.deepface/weights/race_model_single_batch.h5')
  File "C:\Users\timur\AppData\Roaming\Python\Python310\site-packages\keras\utils\traceback_utils.py", 
line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\timur\AppData\Roaming\Python\Python310\site-packages\h5py\_hl\files.py", line 507, in 
__init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\timur\AppData\Roaming\Python\Python310\site-packages\h5py\_hl\files.py", line 220, in 
make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 42482924, sblock->base_addr = 0, stored_eof = 537215296)
```

**Comment by serengil** [comment]
Can you delete this file and try again?

- home+'/.deepface/weights/race_model_single_batch.h5

**Comment by timurturbil** [comment]
I commented out 61th line in Race.py file. And it worked, Thanks. Here this line;
	# race_model.load_weights(home+'/.deepface/weights/race_model_single_batch.h5')

But I didn't understand that why it does return 16 for all different pictures of people. I put my picture you see in my post. it returns ;
{'asian': 16.670958697795868, 'indian': 16.665707528591156, 'black': 16.67257398366928, 'white': 16.668246686458588, 'middle eastern': 16.65269583463669, 'latino hispanic': 16.6698157787323}

And then I put picture of a black person
![black_person](https://user-images.githubusercontent.com/57134662/159118312-238f8a0e-41d6-4429-aa64-93d0d0edeb3e.jpg)

it returned;
{'asian': 16.66196882724762, 'indian': 16.669878363609314, 'black': 16.66347086429596, 'white': 16.668862104415894, 'middle eastern': 16.674646735191345, 'latino hispanic': 16.66116714477539}

Does it work right ?

**Comment by serengil** [comment]
That is because you disabled the weight loading step. That is a must. Otherwise, network will predict randomly.

Library basically downloads the weights from here: https://github.com/serengil/deepface_models/releases/download/v1.0/race_model_single_batch.h5

And copy to the ~/.deepface/weights/race_model_single_batch.h5 path. You can do this manually.
