### ISSUE TITLE
Cannot import name deepface

### ISSUE THREAD

**Issue by sourdurian** [serengil/deepface#5]
Hi there! 

I have ran into a similar issue as the previous guy and have also did the same things. But i'm running on Mac OS. 

ImportError: cannot import name 'DeepFace' from 'deepface' (/Users/oha/anaconda3/lib/python3.7/site-packages/deepface/__init__.py)

```
!pip install deepface
from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt
from tensorflow import keras

Requirement already satisfied: deepface in /Users/oha/anaconda3/lib/python3.7/site-packages (0.0.9)
Requirement already satisfied: gdown>=3.10.1 in /Users/oha/anaconda3/lib/python3.7/site-packages (from deepface) (3.10.1)
```

Any idea how to fix this? 

Thanks!

**Comment by serengil** [comment]
You run this on a virtual environment? Because I run deepface on anaconda and my virtual environment is tensorflow. Before running deepface, I have to call "activate tensorflow" then I call deepface related code.

**Comment by serengil** [comment]
When I call "pip install deepface", then it is installed into the path "C:\Users\sefik\AppData\Local\Continuum\anaconda3\envs\tensorflow\Lib\site-packages\deepface"

When I go to this directory

basemodels (folder)
commons (folder)
extendedmodels (folder)
__init__.py
DeepFace.py

Could you share the directory structure of path /Users/oha/anaconda3/lib/python3.7/site-packages/deepface/ . Downstrokes (_) would not appear?

**Comment by sourdurian** [comment]
Hello Serengil, 

When i pip install deepface, it goes to 

```
(base) xyz-MacBook-Air:~ oha$ python -c "import deepface as _; print(_.__path__)"
['/Users/oha/anaconda3/lib/python3.7/site-packages/deepface']
```

These are the contents in deepface folder. 
__init__.py
__pycache__
basemodels
commons
DeepFace.py
extendedmodels

Thanks!

**Comment by sourdurian** [comment]
Also, i went into the DeepFace.py file and saw the first few lines of code 

```
from deepface.basemodels import VGGFace, OpenFace, Facenet, FbDeepFace
from deepface.extendedmodels import Age, Gender, Race, Emotion
```

I dont see any DeepFace module thats why maybe executing ```from deepface import DeepFace``` is not working?

**Comment by serengil** [comment]
No, this is not the problem because you have basemodels and extendedmodels folders as well.

**Comment by serengil** [comment]
Same issue with the following item

https://github.com/serengil/deepface/issues/3#issuecomment-611404075

**Comment by AmitSharma1127** [comment]
same issue.. it's weird why isn't this working

**Comment by wojtaaspl** [comment]
I`ve had same problem. Rename your project file from deepface.py  e.g. on deepface2.py :)

**Comment by LiZhiHao97** [comment]
> I`ve had same problem. Rename your project file from deepface.py e.g. on deepface2.py :)

Thank you. I made the same mistake.

**Comment by oliversunde** [comment]
Hey, I am struggling with the same, is there a tutorial of what needs to be done when using deepface in for instance Anaconda running on Windows?

I think I am only missing maybe the path to deepface, but not sure where or how to solve it

**Comment by Adesoji1** [comment]
i am still having this issue in the python 3.8 environment, what should I do?

**Comment by Adesoji1** [comment]
PYTHON 3.8 ENVIRONMENT

 from deepface import Deepface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Deepface' from 'deepface' (C:\Users\Glodaris\deep_envface\lib\site-packages\deepface\__init__.py)  @serengil @wojtaaspl  , what exactly do i do?

**Comment by serengil** [comment]
@Adesoji1 it should be DeepFace instead of Deepface

**Comment by Adesoji1** [comment]
Thanks @serengil

**Comment by spoodzxs2345** [comment]
@serengil I used `from deepface import DeepFace` and I get this error message: `ImportError: DLL load failed while importing _pywrap_tf2: A dynamic link library (DLL) initialization routine failed.`

deepface was installed succesfully through `pip install deepface`.

**Comment by serengil** [comment]
@spoodzxs2345 seems your tf installation is not okay: https://stackoverflow.com/questions/49932993/importerror-dll-load-failed-a-dynamic-link-library-dll-initialization-routin

**Comment by Rishabharoraucd** [comment]
I am getting the below error when trying to run this command.
from deepface.commons import distance as dst

ImportError: cannot import name 'distance' from 'deepface.commons' (/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/deepface/commons/__init__.py)

<img width="1136" alt="image" src="https://github.com/serengil/deepface/assets/160285946/b948bc1d-f755-45aa-9aee-653672d726bb">


Can anyone please help me?

**Comment by Rishabharoraucd** [comment]
Hi @serengil ,
Thanks for suggesting the workaround for the previous issue. I am encountering another issue.

TypeError: issubclass() arg 1 must be a class

<img width="967" alt="image" src="https://github.com/serengil/deepface/assets/160285946/31217342-6625-4449-b386-c77d1211e18a">


Could you please share what might be causing this and how to resolve it? thanks

**Comment by serengil** [comment]
@Rishabharoraucd would you please share all exception message from terminal? i cannot see anything related to deepface from that part. Also, sharing your code snippet would be helpful.

**Comment by Rishabharoraucd** [comment]
Hi,
Attaching everything returned from terminal as. a text here as the entire snipped was not possible.

(LIP) rishabharora@Rishs-MBP HeyGenClone % python translate.py 'Green Screen.mp4' russian -o 'done.mp4'
Traceback (most recent call last):
  File "/Users/rishabharora/Documents/GitHub/HeyGenClone/translate.py", line 5, in <module>
    from core.engine import Engine
  File "/Users/rishabharora/Documents/GitHub/HeyGenClone/core/engine.py", line 20, in <module>
    from core.whisperx.asr import load_model, load_audio
  File "/Users/rishabharora/Documents/GitHub/HeyGenClone/core/whisperx/asr.py", line 12, in <module>
    from .vad import load_vad_model, merge_chunks
  File "/Users/rishabharora/Documents/GitHub/HeyGenClone/core/whisperx/vad.py", line 9, in <module>
    from pyannote.audio import Model
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/audio/core/inference.py", line 36, in <module>
    from pyannote.audio.core.model import Model, Specifications
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/audio/core/model.py", line 47, in <module>
    from pyannote.audio.core.task import (
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/audio/core/task.py", line 43, in <module>
    from pyannote.database import Protocol
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/database/__init__.py", line 36, in <module>
    from .registry import registry, LoadingMode
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/database/registry.py", line 38, in <module>
    from .custom import create_protocol, get_init
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/database/custom.py", line 66, in <module>
    from .loader import load_lst, load_trial
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pyannote/database/loader.py", line 44, in <module>
    from spacy.tokens import Token
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/training/__init__.py", line 11, in <module>
    from .callbacks import create_copy_from_base_model  # noqa: F401
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/training/callbacks.py", line 3, in <module>
    from ..language import Language
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/language.py", line 25, in <module>
    from .training.initialize import init_vocab, init_tok2vec
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/training/initialize.py", line 14, in <module>
    from .pretrain import get_tok2vec_ref
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/training/pretrain.py", line 16, in <module>
    from ..schemas import ConfigSchemaPretrain
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/spacy/schemas.py", line 216, in <module>
    class TokenPattern(BaseModel):
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pydantic/main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pydantic/fields.py", line 411, in infer
    return cls(
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pydantic/fields.py", line 451, in prepare
    self._type_analysis()
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pydantic/fields.py", line 545, in _type_analysis
    self._type_analysis()
  File "/opt/anaconda3/envs/LIP/lib/python3.9/site-packages/pydantic/fields.py", line 550, in _type_analysis
    if issubclass(origin, Tuple):  # type: ignore
  File "/opt/anaconda3/envs/LIP/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
(LIP) rishabharora@Rishs-MBP HeyGenClone %

**Comment by serengil** [comment]
error is not coming from deepface at all

**Comment by RosMengHeang** [comment]
hi why there are no functions in deepface.commons
![image](https://github.com/serengil/deepface/assets/141903541/784d31b8-b8bb-4a1c-80ee-ee2d92435a9c)
