### ISSUE TITLE
Error: Tensorflow

### ISSUE THREAD

**Issue by goldentechie** [serengil/deepface#552]
I was trying to use the terminal tool and got this error:
`ModuleNotFoundError: No module named 'tensorflow.python.trackable`
Python version: 2.7.18
OS: Ubuntu 20.04
```
deepface analyze -img_path ~/SMILE_5307421.jpg
Traceback (most recent call last):
  File "/home/hannibal/.local/bin/deepface", line 5, in <module>
    from deepface.DeepFace import cli
  File "/home/hannibal/.local/lib/python3.8/site-packages/deepface/DeepFace.py", line 16, in <module>
    from deepface.basemodels import VGGFace, OpenFace, Facenet, Facenet512, FbDeepFace, DeepID, DlibWrapper, ArcFace, Boosting, SFaceWrapper
  File "/home/hannibal/.local/lib/python3.8/site-packages/deepface/basemodels/VGGFace.py", line 5, in <module>
    from deepface.commons import functions
  File "/home/hannibal/.local/lib/python3.8/site-packages/deepface/commons/functions.py", line 24, in <module>
    from tensorflow.keras.preprocessing.image import load_img, save_img, img_to_array
  File "/home/hannibal/.local/lib/python3.8/site-packages/keras/api/_v2/keras/__init__.py", line 12, in <module>
    from keras import __version__
  File "/home/hannibal/.local/lib/python3.8/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/hannibal/.local/lib/python3.8/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/hannibal/.local/lib/python3.8/site-packages/keras/engine/functional.py", line 27, in <module>
    from keras.dtensor import layout_map as layout_map_lib
  File "/home/hannibal/.local/lib/python3.8/site-packages/keras/dtensor/layout_map.py", line 25, in <module>
    from keras.dtensor import lazy_variable
  File "/home/hannibal/.local/lib/python3.8/site-packages/keras/dtensor/lazy_variable.py", line 26, in <module>
    from tensorflow.python.trackable import base as trackable
ModuleNotFoundError: No module named 'tensorflow.python.trackable'
```

**Comment by serengil** [comment]
use python 3.7
