### ISSUE TITLE
Executing unit_tests.py on Windows 11 runs into h5py issue

### ISSUE THREAD

**Issue by marksmayo** [serengil/deepface#559]
I'm attempting to run the unit tests before I consider playing with making some changes - gotta at least get those running!

However, when I run I get an issue about h5py:

Traceback (most recent call last):
  File "C:\Users\markm\GitHub\deepface\tests\unit_tests.py", line 229, in <module>
    test_cases()
  File "C:\Users\markm\GitHub\deepface\tests\unit_tests.py", line 68, in test_cases
    embedding = DeepFace.represent(img_path)
  File "C:\Python310\lib\site-packages\deepface\DeepFace.py", line 746, in represent
    model = build_model(model_name)
  File "C:\Python310\lib\site-packages\deepface\DeepFace.py", line 63, in build_model
    model = model()
  File "C:\Python310\lib\site-packages\deepface\basemodels\VGGFace.py", line 85, in loadModel
    model.load_weights(output)
  File "C:\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python310\lib\site-packages\h5py\_hl\files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Python310\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

I've tried pip uninstalling and reinstalling h5py to no avail.  It's not a module I'm familiar with and certainly haven't touched it.  I've made no other changes to the repo either so presume it happens for others.

Env: Windows 11

**Comment by serengil** [comment]
weights are stored in ~/.deepface/weights

maybe weight file is broken while installing. try to delete this folder and re-run deepface.
