### ISSUE TITLE
Getting weights dir already existing error

### ISSUE THREAD

**Issue by KaushikSathvara** [serengil/deepface#579]
Getting error while making docker container up

```
worker-1  |   File "/usr/local/lib/python3.8/site-packages/deepface/commons/functions.py", line 56, in initialize_folder
worker-1  |     os.makedirs(home+"/.deepface/weights")
worker-1  |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
worker-1  |     mkdir(name, mode)
-worker-1  | FileExistsError: [Errno 17] File exists: '/root/.deepface/weights'
```
So I have to manualy remove directory while running above script.

Let me know if someone knows the solution of this.

**Comment by serengil** [comment]
interesting because that command is run when folder is not available.

```python
if not os.path.exists(home+"/.deepface/weights"):
   os.makedirs(home+"/.deepface/weights")
```

**Comment by serengil** [comment]
closed because of inactivity

**Comment by alejamp** [comment]
I got the same error in a GCP Cloud Run Deploy. When I run it on my Mac OS 12.4 it works perfect.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/main.py", line 9, in <module>
    from deepface import DeepFace
  File "/usr/local/lib/python3.8/dist-packages/deepface/DeepFace.py", line 838, in <module>
    functions.initialize_folder()
  File "/usr/local/lib/python3.8/dist-packages/deepface/commons/functions.py", line 35, in initialize_folder
    os.makedirs(home + "/.deepface")
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/.deepface'
---------------------------------------

May be if deepface changes 

```os.makedirs(home + "/.deepface")``` 

by 

```os.makedirs(filePath, exist_ok=True)```

**Comment by serengil** [comment]
most probably two parallel threads are trying to run that command and got that exception

@alejamp your solution will work anyway. do you want to create a PR? will be happy to merge.
