### ISSUE TITLE
raise ValueError("Confirm that opencv is installed on your environment! Expected path ",face_detector_path," violated.")

### ISSUE THREAD

**Issue by michaelmoreno** [serengil/deepface#595]
I attempt to analyze a picture of a face
```py
analysis = DeepFace.analyze("facepic.png", actions=['race', 'gender'])
```
Python crashes with the following error
```
Metal device set to: Apple M2

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

Action: race:   0%|                                                                                                                                                              | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/michaelmoreno/pers/date-maxxer/main.py", line 33, in <module>
    main()
  File "/Users/michaelmoreno/pers/date-maxxer/main.py", line 13, in main
    analysis = DeepFace.analyze("temp/bumble.png", actions=['race', 'gender'])
  File "/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/deepface/DeepFace.py", line 432, in analyze
    img_224, region = functions.preprocess_face(img = img_path, target_size = (224, 224), grayscale = False, enforce_detection = enforce_detection, detector_backend = detector_backend, return_region = True) #just emotion model expects grayscale images
  File "/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/deepface/commons/functions.py", line 178, in preprocess_face
    img, region = detect_face(img = img, detector_backend = detector_backend, grayscale = grayscale, enforce_detection = enforce_detection, align = align)
  File "/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/deepface/commons/functions.py", line 110, in detect_face
    face_detector = FaceDetector.build_model(detector_backend)
  File "/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/deepface/detectors/FaceDetector.py", line 27, in build_model
    face_detector = face_detector()
  File "/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/deepface/detectors/OpenCvWrapper.py", line 10, in build_model
    detector["face_detector"] = build_cascade('haarcascade')
  File "/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/deepface/detectors/OpenCvWrapper.py", line 23, in build_cascade
    raise ValueError("Confirm that opencv is installed on your environment! Expected path ",face_detector_path," violated.")
ValueError: ('Confirm that opencv is installed on your environment! Expected path ', '/Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/data/haarcascade_frontalface_default.xml', ' violated.')
```
I seem to have `opencv` installed by both conda and pip
```
conda list | grep opencv
libopencv                 4.5.5            py31hb029696_7    conda-forge
opencv                    4.5.5            py31hb6292c7_7    conda-forge
py-opencv                 4.5.5            py31h69fb684_7    conda-forge

python -m pip list | grep opencv
opencv-python           4.5.5
```

I am on an M2 MacBook Pro 2022 using `miniforge` for conda.

Here are the contents of my `environment.yml`
```
name: /Users/michaelmoreno/pers/date-maxxer/env
channels:
  - apple
  - defaults
  - conda-forge
dependencies:
  - aom=3.5.0=h7ea286d_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - brotlipy=0.7.0=py310h8e9501a_1005
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h73a0509_1014
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2399d43_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=38.0.3=py310hfc83b78_0
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=4.4.2=gpl_hf4c414c_110
  - filelock=3.8.0=pyhd8ed1ab_0
  - fire=0.4.0=pyh44b312d_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hd633e50_0
  - gdown=4.5.3=pyhd8ed1ab_0
  - gettext=0.21.1=h0186832_0
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.13=h9f76cd9_1001
  - grpcio=1.46.3=py310ha26ec5d_0
  - h5py=3.6.0=nompi_py310hb8bbf05_100
  - harfbuzz=4.4.1=hd36a07e_0
  - hdf5=1.12.1=nompi_hd9dbc9e_104
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - jasper=2.0.33=hba35424_0
  - jpeg=9e=he4db4b2_2
  - krb5=1.19.3=he492e65_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.86.0=h1c293e1_1
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=hc377ac9_4
  - libgfortran=5.0.0=11_3_0_hd922786_26
  - libgfortran5=11.3.0=hdaf2cc0_26
  - libglib=2.74.1=h4646484_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.47.0=h519802c_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.5.5=py31hb029696_7
  - libpng=1.6.38=h76d750c_0
  - libprotobuf=3.19.4=hccf11d3_0
  - libsqlite=3.39.4=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.4.0=hfa0b094_4
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.4=h7cfbb63_0
  - ncurses=6.3=h1a28f6b_3
  - nettle=3.8.1=h63371fa_1
  - numpy=1.23.2=py310h127c7cf_0
  - opencv=4.5.5=py31hb6292c7_7
  - openh264=2.3.1=hb7217d7_1
  - openssl=3.0.7=h03a7124_0
  - p11-kit=0.24.1=h29577a5_0
  - pandas=1.5.1=py310h2b830bf_1
  - pcre2=10.40=hb34f9b4_0
  - pip=22.2.2=py310hca03da5_0
  - pixman=0.40.0=h27ca646_0
  - protobuf=3.19.4=py310h1b49c16_0
  - py-opencv=4.5.5=py31h69fb684_7
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=hae75cb6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=0.21.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.6=pyhd8ed1ab_0
  - readline=8.2=h1a28f6b_0
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=65.5.0=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.3=h1058600_0
  - svt-av1=1.3.0=h7ea286d_0
  - tensorflow-deps=2.10.0=0
  - termcolor=2.1.0=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - tzdata=2022f=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.2.6=h1a28f6b_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
    - absl-py==1.3.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==22.1.0
    - cachetools==5.2.0
    - deepface==0.0.75
    - exceptiongroup==1.0.1
    - flatbuffers==22.10.26
    - gast==0.4.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - h11==0.14.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - outcome==1.2.0
    - packaging==21.3
    - pillow==9.3.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - selenium==4.6.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-macos==2.10.0
    - tensorflow-metal==0.6.0
    - trio==0.22.0
    - trio-websocket==0.9.2
    - typing-extensions==4.4.0
    - undetected-chromedriver==3.1.6
    - urllib3==1.26.12
    - websockets==10.4
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - wsproto==1.2.0
prefix: /Users/michaelmoreno/pers/date-maxxer/env
```

**Comment by serengil** [comment]
Exception message is clear. You do not have this file: /Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/data/haarcascade_frontalface_default.xml

**Comment by michaelmoreno** [comment]
> Exception message is clear. You do not have this file: /Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/data/haarcascade_frontalface_default.xml

Yes, that part is clear. What's not clear is how I am supposed to generate that file. The error suggests that it has to do with `opencv` not being installed, but as I showed in my post, both `conda` and `pip` have it installed already.

**Comment by serengil** [comment]
this file must be installed somewhere else. search it in your local system.

**Comment by michaelmoreno** [comment]
> this file must be installed somewhere else. search it in your local system.

Yes, this is the result of `locate haarcascade_frontalface_default.xml`     
``` 
/opt/homebrew/Caskroom/miniforge/base/pkgs/libopencv-4.5.5-py31hb029696_7/share/opencv4/haarcascades/haarcascade_frontalface_default.xml
/opt/homebrew/lib/python3.10/site-packages/cv2/data/haarcascade_frontalface_default.xml
/opt/homebrew/lib/python3.11/site-packages/cv2/data/haarcascade_frontalface_default.xml
```
How should I proceed, just run `cp /opt/homebrew/lib/python3.10/site-packages/cv2/data/haarcascade_frontalface_default.xml /Users/michaelmoreno/pers/date-maxxer/env/lib/python3.10/site-packages/data/haarcascade_frontalface_default.xml`?

**Comment by surya-narayanan** [comment]
it turns out that if you install using conda, the path to the file is 

`.../miniconda3/pkgs/libopencv-4.7.0-py38h0a50863_4/share/opencv4/haarcascades/haarcascade_frontalface_default.xml`

which is not where the package looks for it

**Comment by elshaddd** [comment]
> > this file must be installed somewhere else. search it in your local system.
> 
> Yes you were right, this is the result of `locate haarcascade_frontalface_default.xml`
> 
> ```
> /opt/homebrew/Caskroom/miniforge/base/pkgs/libopencv-4.5.5-py31hb029696_7/share/opencv4/haarcascades/haarcascade_frontalface_default.xml
> /opt/homebrew/lib/python3.10/site-packages/cv2/data/haarcascade_frontalface_default.xml
> /opt/homebrew/lib/python3.11/site-packages/cv2/data/haarcascade_frontalface_default.xml
> ```

> I have cp it into the desired directory, but am still getting the error.
@michaelmoreno How did you solve this problem??

**Comment by elshaddd** [comment]
> > this file must be installed somewhere else. search it in your local system.
> 
> Yes you were right, this is the result of `locate haarcascade_frontalface_default.xml`
> 
> ```
> /opt/homebrew/Caskroom/miniforge/base/pkgs/libopencv-4.5.5-py31hb029696_7/share/opencv4/haarcascades/haarcascade_frontalface_default.xml
> /opt/homebrew/lib/python3.10/site-packages/cv2/data/haarcascade_frontalface_default.xml
> /opt/homebrew/lib/python3.11/site-packages/cv2/data/haarcascade_frontalface_default.xml
> ```

@michaelmoreno how did you solve this problem?

**Comment by hut8** [comment]
Is there a simple way to get deepface to look in the proper place? Mine is at `/usr/local/share/opencv4/haarcascades/haarcascade_frontalface_default.xml` but deepface looks in `/usr/local/lib/python3.10/site-packages/cv2/data/haarcascade_frontalface_default.xml`

**Comment by returnv01d** [comment]
I have the same problem. Installed opencv using conda and I have the file but in `libopencv`
