### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.layers.merge'

### ISSUE THREAD

**Issue by botzill** [serengil/deepface#602]
Installing this one python3.8 and I get the following error when I call `analyze`.

```
Traceback (most recent call last):
  File "index.py", line 5, in <module>
    from function import handler
  File "/home/app/function/handler.py", line 3, in <module>
    from .df import DeepFaceFunctions
  File "/home/app/function/df.py", line 8, in <module>
    from deepface import DeepFace
  File "/home/app/python/deepface/DeepFace.py", line 16, in <module>
    from deepface.basemodels import VGGFace, OpenFace, Facenet, FbDeepFace
  File "/home/app/python/deepface/basemodels/OpenFace.py", line 11, in <module>
    from keras.layers.merge import Concatenate
ModuleNotFoundError: No module named 'keras.layers.merge'
```

**Comment by serengil** [comment]
exception message is clear. your keras dependency seems not okay.

**Comment by botzill** [comment]
Yes I understand but I do install the dependencies set in the project, maybe I need to change some versions ?
