### ISSUE TITLE
On Mac it works fine where are as AWS Sagemaker it throws an error. 

### ISSUE THREAD

**Issue by thehellmaker** [serengil/deepface#607]
The below code works fine on a macos but same simple code with same exact input errors out on AWS Sagemaker running on instance type ml.g4dn.xlarge, ml.c5.xlarge and ml.p3.2xlarge. 
Python version tested on both 3.7 and 3.10

```
from time import time
from deepface import DeepFace

sum = 0
count = 0

for i in range(1, 10):
    start_time = time()
    result = DeepFace.verify(img1_path = "expected.jpg", img2_path = "actual.jpg")
    print(result)
    end_time = time()
    sum += (end_time - start_time)
    count += 1
    
print("Average Inference Time", sum / count)
```

Directory  /home/ec2-user /.deepface created
Directory  /home/ec2-user /.deepface/weights created
Traceback (most recent call last):
  File "FaceVerificationTest.py", line 9, in <module>
    result = DeepFace.verify(img1_path = "expected.jpg", img2_path = "actual.jpg")
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/deepface/DeepFace.py", line 133, in verify
    model = build_model(model_name)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/deepface/DeepFace.py", line 63, in build_model
    model = model()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/deepface/basemodels/VGGFace.py", line 72, in loadModel
    model = baseModel()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/deepface/basemodels/VGGFace.py", line 32, in baseModel
    model.add(MaxPooling2D((2,2), strides=(2,2)))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1967, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "max_pooling2d_1" (type MaxPooling2D).

Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NCHW", explicit_paddings=[], ksize=[1, 1, 2, 2], padding="VALID", strides=[1, 1, 2, 2]](Placeholder)' with input shapes: [?,128,112,1].

Call arguments received by layer "max_pooling2d_1" (type MaxPooling2D):
  • inputs=tf.Tensor(shape=(None, 128, 112, 1), dtype=float32)

**Comment by liechtym** [comment]
Having the same issue

**Comment by liechtym** [comment]
Solved it by adding this code:
```
import tensorflow as tf
tf.keras.backend.set_image_data_format('channels_last')
```
