### ISSUE TITLE
Deepface.analyze doesn't process frame

### ISSUE THREAD

**Issue by KentaroJay** [serengil/deepface#674]
Hi, I'm on a project where I have to analyze a person's emotion. I've build dev environment using docker according to this document(https://docs.opencv.org/4.x/d2/de6/tutorial_py_setup_in_ubuntu.html)
Here's my code(slightly edited for disclosure) 

```
video = cv2.VideoCapture('somevideo.mp4')
while video.isOpened():
            ret, frame = video.read()
            if ret is True:
                emotion = json.loads(DeepFace.analyze(frame, actions=["emotion"], enforce_detection=False))[0]["dominant_emotion"]
                ~~~~do something ~~~~
            else:
                break
```

When I run this code, I got this error below.

```
Traceback (most recent call last):
  File "attach_label_to_video.py", line 124, in <module>
    AttachText(path="assets/samp002.mp4").main()
  File "attach_label_to_video.py", line 29, in main
    self.process_video()
  File "attach_label_to_video.py", line 57, in process_video
    self.required_operations(frame)
  File "attach_label_to_video.py", line 100, in required_operations
    display_text = self.get_dominant_emotion(frame)
  File "attach_label_to_video.py", line 79, in get_dominant_emotion
    return json.loads(DeepFace.analyze(frame, actions=["emotion"]))[0][
  File "/usr/local/lib/python3.6/site-packages/deepface/DeepFace.py", line 277, in analyze
    emotion_predictions = models['emotion'].predict(img_gray, verbose=0)[0,:]
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1751, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:1586 predict_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:1569 run_step  **
        outputs = model.predict_step(data)
    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:1537 predict_step
        return self(x, training=False)
    /usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.6/site-packages/keras/engine/input_spec.py:234 assert_input_compatibility
        str(tuple(shape)))

    ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (None, 48, 48)
````

I'd be very happy if you tell me what is going on here.

**Comment by KentaroJay** [comment]
I tried reshaping dimension by the code below
``` 
frame = np.expand_dims(frame, 0)
```
but it raised another error 
```
Traceback (most recent call last):
  File "attach_label_to_video.py", line 125, in <module>
    AttachText(path="assets/samp002.mp4").main()
  File "attach_label_to_video.py", line 29, in main
    self.process_video()
  File "attach_label_to_video.py", line 57, in process_video
    self.required_operations(frame)
  File "attach_label_to_video.py", line 101, in required_operations
    display_text = self.get_dominant_emotion(frame)
  File "attach_label_to_video.py", line 81, in get_dominant_emotion
    DeepFace.analyze(frame, actions=["emotion"], enforce_detection=False)
  File "/usr/local/lib/python3.6/site-packages/deepface/DeepFace.py", line 261, in analyze
    img_objs = functions.extract_faces(img=img_path, target_size=(224, 224), detector_backend=detector_backend, grayscale = False, enforce_detection=enforce_detection, align=align)
  File "/usr/local/lib/python3.6/site-packages/deepface/commons/functions.py", line 116, in extract_faces
    current_img = cv2.resize(current_img, dsize)
cv2.error: OpenCV(4.7.0) /tmp/pip-install-k6hq3vdj/opencv-python_f8b90b56b1884ebfae3eb4b6fc2093cb/opencv/modules/imgproc/src/resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
```

**Comment by KentaroJay** [comment]
It was the Python version that was not going well with this library. I upgraded python to newer version and then the error was fixed. Thank you. 
Closing this issue
