### ISSUE TITLE
Unicode characters?

### ISSUE THREAD

**Issue by bsleeman** [serengil/deepface#710]
Hi,

Any calls the extract_faces function that contain (at least this unicode  character é) fail.

DeepFace.extract_faces(r"V:\Netlife_Retouching\Catholic Ladies' College - Eltham\2023\Portraits\7E\Amelia Mummé.jpg")
  
Traceback (most recent call last):
  File "<pyshell#45>", line 1, in <module>
    DeepFace.extract_faces(r"V:\Netlife_Retouching\Catholic Ladies' College - Eltham\2023\Portraits\7E\Amelia Mummé.jpg")
  File "C:\Users\PrintRoom\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "C:\Users\PrintRoom\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\commons\functions.py", line 105, in extract_faces
    img_region = [0, 0, img.shape[1], img.shape[0]]
AttributeError: 'NoneType' object has no attribute 'shape'

deepface 0.0.79
Windows10

Regards

**Comment by bsleeman** [comment]
Hi, further investigation has narrowed it down to the cv2.imread function being the failing culprit.

Regards,

**Comment by serengil** [comment]
Cannot reproduce this in Debian

**Comment by bsleeman** [comment]
Maybe only an issue with Windows? 
Have worked around it by processing the file into a numpty array.

**Comment by serengil** [comment]
this is done with the latest PR
