### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ehsaneshaghi** [serengil/deepface#723]
I get the following error when executing the docker image:
`Illegal instruction (core dumped)`

How to reproduce the error :

```
docker build -t deepface .
docker run -it --net="host" deepface bash
```
inside the docker container run:
```
deepface
```

when I run the docker without interactive mode I get this error:
`[WARNING] Worker with pid 8 was terminated due to signal 4`

How to reproduce this message:

```
docker build -t deepface . 
docker run --net="host" deepface
```
complete log:

```
[2023-04-18 09:58:45 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-04-18 09:58:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2023-04-18 09:58:45 +0000] [1] [INFO] Using worker: sync
[2023-04-18 09:58:45 +0000] [8] [INFO] Booting worker with pid: 8
[2023-04-18 09:58:48 +0000] [1] [WARNING] Worker with pid 8 was terminated due to signal 4
[2023-04-18 09:58:48 +0000] [24] [INFO] Booting worker with pid: 24
[2023-04-18 09:58:52 +0000] [1] [WARNING] Worker with pid 24 was terminated due to signal 4
[2023-04-18 09:58:52 +0000] [40] [INFO] Booting worker with pid: 40
^C[2023-04-18 09:58:53 +0000] [1] [INFO] Handling signal: int
[2023-04-18 09:58:55 +0000] [1] [WARNING] Worker with pid 40 was terminated due to signal 4
```

my hardware:

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          15
Model:               6
Model name:          Common KVM processor
Stepping:            1
CPU MHz:             2294.608
BogoMIPS:            4589.21
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-7
NUMA node1 CPU(s):   8-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
```

**Comment by shockagent** [comment]
same error in a clean python:3.8 container:
as a root (python:3.8 container) I have installed
`apt-get install ffmpeg libsm6 libxext6 -y --no-install-recommends`
then
`pip install deepface`
finally I entered in a Python CLI:

```python
>>> from deepface import DeepFace
Illegal instruction (core dumped)
```

**Comment by shockagent** [comment]
following up #871 

I confirm that `Illegal instruction (core dumped)` error is caused by AVX instructions in TensorFlow when executed on a CPU without AVX capabilities: I have compiled TensorFlow from sources (about 12 hours !), release 2.16.0, for python 3.11, then installed it with pip.
I also installed deepface requirements: now I can import tensorflow without `Illegal instruction (core dumped)`.

But if I try `python api.py`, there is a problem with keras:
```python
/app# python api.py
2023-10-28 16:27:42.509859: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/app/api.py", line 2, in <module>
    import app
  File "/app/app.py", line 3, in <module>
    from routes import blueprint
  File "/app/routes.py", line 2, in <module>
    import service
  File "/app/service.py", line 1, in <module>
    from deepface import DeepFace
  File "/app/deepface/DeepFace.py", line 18, in <module>
    from deepface.basemodels import (
  File "/app/deepface/basemodels/VGGFace.py", line 4, in <module>
    from deepface.commons import functions
  File "/app/deepface/commons/functions.py", line 27, in <module>
    from tensorflow.keras.preprocessing import image
  File "/usr/local/lib/python3.11/site-packages/keras/api/_v2/keras/__init__.py", line 3, in <module>
    from keras.api._v2.keras import __internal__
  File "/usr/local/lib/python3.11/site-packages/keras/__init__.py", line 3, in <module>
    from keras import __internal__
  File "/usr/local/lib/python3.11/site-packages/keras/__internal__/__init__.py", line 3, in <module>
    from keras.__internal__ import backend
  File "/usr/local/lib/python3.11/site-packages/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
  File "/usr/local/lib/python3.11/site-packages/keras/src/__init__.py", line 21, in <module>
    from keras.src import models
  File "/usr/local/lib/python3.11/site-packages/keras/src/models/__init__.py", line 18, in <module>
    from keras.src.engine.functional import Functional
  File "/usr/local/lib/python3.11/site-packages/keras/src/engine/functional.py", line 25, in <module>
    from keras.src import backend
  File "/usr/local/lib/python3.11/site-packages/keras/src/backend/__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/usr/local/lib/python3.11/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/usr/local/lib/python3.11/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import ALLOWED_DTYPES
  File "/usr/local/lib/python3.11/site-packages/keras/src/backend/common/variables.py", line 9, in <module>
    from keras.src.utils.naming import auto_name
  File "/usr/local/lib/python3.11/site-packages/keras/src/utils/__init__.py", line 53, in <module>
    from keras.src.utils.feature_space import FeatureSpace
  File "/usr/local/lib/python3.11/site-packages/keras/src/utils/feature_space.py", line 20, in <module>
    from keras.src.engine import base_layer
  File "/usr/local/lib/python3.11/site-packages/keras/src/engine/base_layer.py", line 32, in <module>
    from keras.src import constraints
  File "/usr/local/lib/python3.11/site-packages/keras/src/constraints/__init__.py", line 4, in <module>
    from keras.src.constraints.constraints import Constraint
  File "/usr/local/lib/python3.11/site-packages/keras/src/constraints/constraints.py", line 2, in <module>
    from keras.src import ops
  File "/usr/local/lib/python3.11/site-packages/keras/src/ops/__init__.py", line 5, in <module>
    from keras.src.backend import cast
ImportError: cannot import name 'cast' from partially initialized module 'keras.src.backend' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/keras/src/backend/__init__.py)
``` 

any suggestions ?

Moreover: is `ffmpeg` package required ? I still can't test deepface so I cannot test this error:
`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`
but if deepface needs just the module libGL.so.1, then the libgl1 package is enough

**Comment by shockagent** [comment]
I succesfully managed to compile tensorflow and install deepface !
Tensorflow newer releases are compiled for python3.11, so I tryed a slightly older release: 2.13.1 that is compiled for python3.8.
I compiled from sources in a python3.8 venv and obtained this file: tensorflow-2.13.1-cp38-cp38-linux_x86_64.whl.
I haven't done extensive testing, however deepface starts correctly.

I installed only [libgl1](https://packages.debian.org/bookworm/libgl1)

I uploaded tensorflow wheels NO-AVX either for python3.11 and python3.8: https://github.com/shockagent/tensorflow-noavx/releases

**Comment by shockagent** [comment]
deepface is working perfectly with my compiled tensorflow wheel without AVX.
I forked the original repo: https://github.com/shockagent/deepface-noavx (if there is something wrong with it, please contact me) and made some changes in order to create a working dockerfile. 

I had to install deepface from pip, because there are still some compatibility issues with the sources: I ask developers to upgrade deepface to latest python releases.
