### ISSUE TITLE
ValueError: Error when checking input: expected conv2d_49_input to have 4 dimensions, but got array with shape (1, 48, 48)

### ISSUE THREAD

**Issue by Darrshan-Sankar** [serengil/deepface#727]
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    DeepFace.stream(db_path = "C:/Users/Admin/Desktop/database")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\deepface\DeepFace.py", line 744, in stream
    frame_threshold=frame_threshold,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\deepface\commons\realtime.py", line 180, in analysis
    silent=True,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\deepface\DeepFace.py", line 336, in analyze
    emotion_predictions = models["emotion"].predict(img_gray, verbose=0)[0, :]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected conv2d_49_input to have 4 dimensions, but got array with shape (1, 48, 48)

**Comment by serengil** [comment]
please use the source code instead of pip version. this bug is fixed but i have not published it to pip yet.

```python
$ git clone https://github.com/serengil/deepface.git
$ cd deepface
$ pip install -e .
```

**Comment by Darrshan-Sankar** [comment]
Thank you for the clarification sir.
