### ISSUE TITLE
ValueError: Passed db_path does not exist! when trying to perform only face analysis on video

### ISSUE THREAD

**Issue by supanormie** [serengil/deepface#756]
```py
from deepface import DeepFace
DeepFace.stream(source="test/dataset/videoplayback.mp4", enable_face_analysis=True)
```

Is it possible or I have to manually extract a clear frame from the video to perform analysis on top of images?

**Comment by serengil** [comment]
the problem you are not setting any db path
`DeepFace.stream(db_path="some_path", source="test/dataset/videoplayback.mp4", enable_face_analysis=True)`

**Comment by jun297** [comment]
Hi, with "some_path" to db_path, I get an error still
How can I fix this?

```
Traceback (most recent call last):
  File "E:\github\deepface\stream_demo.py", line 13, in <module>
    DeepFace.stream(db_path="empty/", model_name="VGG-Face", detector_backend="retinaface", source="D:/Videos/vis_results/dialogue_1min.mp4", enable_face_analysis=True)
  File "E:\github\deepface\deepface\DeepFace.py", line 738, in stream
    realtime.analysis(
  File "E:\github\deepface\deepface\commons\realtime.py", line 50, in analysis
    DeepFace.find(
  File "E:\github\deepface\deepface\DeepFace.py", line 469, in find
    raise ValueError(
ValueError: ('There is no image in ', 'empty/', ' folder! Validate .jpg or .png files exist in this path.')
```

I tried to set the db_path to a directory that has images (images/),
Although the code worked without an error, where can I check the video results?

Thank you for sharing your nice codebase
