### ISSUE TITLE
ValueError: invalid detector_backend passed - yunet

### ISSUE THREAD

**Issue by richardabear** [serengil/deepface#813]
Trying to use yunet for face detection.

here is my code:

```python
def advance_detect(video_url):
   cap = cv2.VideoCapture(video_url)
   prop_fps = int(cap.get(cv2.CAP_PROP_FPS))
   fps = math.ceil(prop_fps)
   print("FPS:", fps)
   results = []
   frame_count = 0
   frame_limiter = 10
   while True:
      success, frame = cap.read()
      if not success:
         break
      frame_count+=1
      if(frame_count % frame_limiter != 0):
         continue
      faces = DeepFace.extract_faces(frame, enforce_detection=False, detector_backend="yunet")
      face = filter_faces(faces)
      results.append(face)
      if(frame_count > 0):
         timestamp = frame_count / fps
      else:
         timestamp = 0
      print(timestamp)
   return results
  ```

and the error returned is:
```
Traceback (most recent call last):
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/richardabear/Documents/brush-ai/video-tracker/main.py", line 41, in advanced_detection
    results = advanced_detect.advance_detect(video_url)
  File "/Users/richardabear/Documents/brush-ai/video-tracker/advanced_detect.py", line 20, in advance_detect
    faces = DeepFace.extract_faces(frame, enforce_detection=False, detector_backend="yunet")
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/deepface/commons/functions.py", line 110, in extract_faces
    face_detector = FaceDetector.build_model(detector_backend)
  File "/Users/richardabear/.local/share/virtualenvs/video-tracker-acPvatin/lib/python3.9/site-packages/deepface/detectors/FaceDetector.py", line 39, in build_model
    raise ValueError("invalid detector_backend passed - " + detector_backend)
ValueError: invalid detector_backend passed - yunet
```

**Comment by serengil** [comment]
yunet is not available in pip version yet. try to use the source code.

**Comment by richardabear** [comment]
Oh okay thanks

**Comment by diego0718** [comment]
Same error with Yolov8 and Mediapipe, so i build deepface from its source code. In this way the statement from deepface import DeepFace has to be replaced right?. If i want to extract face i need to replace:
    face_objs = DeepFace.extract_faces(
        img_path=img_path,
        target_size=(128, 128),
        detector_backend=backends[-1] for what statement?. Correct me please if im wrong. Its my first day checking the repo
