### ISSUE TITLE
module 'tensorflow.compat.v2' has no attribute '__internal__'

### ISSUE THREAD

**Issue by SmoothHydarlisk** [serengil/deepface#835]
my environment：
--tensorflow==1.14.0
--keras==2.11.0
--python==3.7.12
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from deepface import DeepFace
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/deepface/DeepFace.py", line 16, in <module>
    from deepface.basemodels import VGGFace, OpenFace, Facenet, Facenet512, FbDeepFace, DeepID, DlibWrapper, ArcFace, Boosting, SFaceWrapper
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/deepface/basemodels/VGGFace.py", line 5, in <module>
    from deepface.commons import functions
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/deepface/commons/functions.py", line 18, in <module>
    import keras
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/keras/engine/functional.py", line 26, in <module>
    from keras import backend
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/keras/backend.py", line 32, in <module>
    from keras import backend_config
  File "/home/ecsuser/miniconda3/envs/face/lib/python3.7/site-packages/keras/backend_config.py", line 33, in <module>
    @tf.__internal__.dispatch.add_dispatch_support
AttributeError: module 'tensorflow.compat.v2' has no attribute ### ### '__internal__'
```
I found that it can run normally，when I updated TensorFlow to 2.10.
I would like to know the minimum required version of TensorFlow for this project

**Comment by serengil** [comment]
this is not directly related to deepface. you are having trouble when you importing keras. so, it seems keras 2.11 is not compatible with tf2. for instance, i was using keras 2.2.0 and it was compatible with tf1.x.

the best place to get the answer for this question is the keras forum.
