### ISSUE TITLE
OSError: Unable to synchronously open file

### ISSUE THREAD

**Issue by Cassieyy** [serengil/deepface#886]
Thank you for your great job!!! i've encountered an error when using the age predict api. The detailed info is as follows.

>>> DeepFace.analyze(img_path = "/knt/pengyue.lpy/Silent-Face-Anti-Spoofing/datasets/cy.jpg", actions = ['age'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/deepface/deepface/DeepFace.py", line 320, in analyze
    models["age"] = build_model("Age")
  File "/root/deepface/deepface/DeepFace.py", line 80, in build_model
    model = model()
  File "/root/deepface/deepface/extendedmodels/Age.py", line 53, in loadModel
    age_model.load_weights(home + "/.deepface/weights/age_model_weights.h5")
  File "/opt/conda/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)

I followed the main page step by step, and I am confident that my environment matches the requirements specified in the requirement.txt file. Could you give me some advice?

Look forward for your reply, and thanks in advance!!!

**Comment by serengil** [comment]
File signature not found indicates that Your file is corrupted.

Try to delete this: ~/.deepface/weights/age_model_weights.h5

**Comment by tanim26072000** [comment]
> File signature not found indicates that Your file is corrupted.
> 
> Try to delete this: ~/.deepface/weights/age_model_weights.h5

there is no .deepface found in my python/lib/site-packages directory, and I am facing the same issue

**Comment by flapponi** [comment]
Not sure if this is stillactive, u tI get the same error wehn using the action "emotion"

**Comment by pilotbird-Truphena-Lwanga** [comment]
I am facing the same issue when downloading the weights from here: https://github.com/serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5

**Comment by pilotbird-Truphena-Lwanga** [comment]
Updating to use the deepface==0.0.99 version resolved it for me.
