### ISSUE TITLE
ValueError: Input 0 of layer "model_3" is incompatible with the layer: expected shape=(None, 55, 47, 3), found shape=(None, 47, 55, 3)

### ISSUE THREAD

**Issue by aico-confs** [serengil/deepface#891]
I run the visual-test.py (sample code) in "test " folder

and get error
`---------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\desktop\deepface\tests\visual-test.py", line 20, in <module>
    obj = DeepFace.verify(
  File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\DeepFace.py", line 169, in verify
    img1_embedding_obj = represent(
  File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\DeepFace.py", line 678, in represent
    embedding = model.predict(img, verbose=0)[0].tolist()
  File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\q1233\AppData\Local\Temp\__autograph_generated_file0s0h5cr5.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py", line 2416, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py", line 2401, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py", line 2389, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py", line 2357, in predict_step
        return self(x, training=False)
    File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\q1233\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model_3" is incompatible with the layer: expected shape=(None, 55, 47, 3), found shape=(None, 47, 55, 3)`

Do I should reinstall the model or module?

**Comment by ekkolon** [comment]
Hey there!

This is a possible duplicate:

- #674
- #680 
- #885

Ultimately, you may encounter this error due to an incompatible Python version or package (e.g keras, tensorflow).

##  As a side note

It seems you are running DeepFace on Windows and not using a Python virtual environment, right?

#### If this is the case

I strongly recommend you to use DeepFace from within an isolated environment, e.g. using [virtualenv](https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html).

The minimum Python version for DeepFace is `3.5.5`. For example, the [Dockerfile](https://github.com/serengil/deepface/blob/master/Dockerfile) uses version `3.8`. I'd recommend to go with this one or higher.

Usually, the Python version can be specified when creating a new virtual environment. 

> Regardless of whether you're on Windows, Linux or Mac: always manage your Python project dependencies from within a virtual environment!
