### ISSUE TITLE
`AssertionError` while installing `deepface` via pip

### ISSUE THREAD

**Issue by arrafi-musabbir** [serengil/deepface#929]
I'm trying to install `deepface` library via pip but it fails with AssertionError.

My system specs are:

OS : Pop!_OS 22.04 LTS x86_64 
Python: Python-3.10.12
Pip: pip-22.0.2

I did the following with pip:
```
pip install deepface
```

I also tried to build from the source by following these :
```
git clone https://github.com/serengil/deepface.git
cd deepface
pip install -e .
```
Both of them return the same error. Here's the full error message that I got:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```
Any help would be greatly appreciated!

**Comment by raspcode** [comment]
I spent days on the issue. My suggestion is make sure you only have one version of python installed and make sure it is the correct version supported by the library. In my case I installed python 3.11.7. I deleted my virtual environment, uninstalled all versions of python except this one to make sure there is no confusion of which one is running. It installed fine along with its pre-requisites.

**Comment by arrafi-musabbir** [comment]
Downgrading to an older version solved my issue: 
```
python -m pip install --upgrade pip
pip uninstall deepface -y
pip install dlib==19.24.0
pip install --no-deps deepface==0.0.79
```
