### ISSUE TITLE
getting error while install  deepface pip3 install deepface

### ISSUE THREAD

**Issue by techUdayMungalpara** [serengil/deepface#935]
## Getting error while install deepface
ERROR: Exception:
Traceback (most recent call last):
  File "/home/uday/Desktop/sds/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/uday/Desktop/sds/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/uday/Desktop/sds/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/uday/Desktop/sds/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/uday/Desktop/sds/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError

**Comment by serengil** [comment]
Duplicated - https://github.com/serengil/deepface/issues/929

As explained [here](https://github.com/serengil/deepface/issues/929#issuecomment-1868379368), did you try to upgrade pip?

python -m pip install --upgrade pip
