### ISSUE TITLE
Stream error

### ISSUE THREAD

**Issue by joseg20** [serengil/deepface#966]
I am getting this error when i am trying to use the stream method.

```
You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2024-01-22 22:26:31.428493: W external/local_xla/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:542] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
error: libdevice not found at ./libdevice.10.bc
2024-01-22 22:26:31.428658: E tensorflow/compiler/mlir/tools/kernel_gen/tf_framework_c_interface.cc:207] INTERNAL: Generating device code failed.
2024-01-22 22:26:31.429024: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: JIT compilation failed.
Finding representations:   0%|                                                                                                     | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/jose/Git/Fiona/src/demos/demo_deepface.py", line 3, in <module>
    DeepFace.stream(db_path = "src/demos/data/database")
  File "/home/jose/anaconda3/envs/fiona_test_env/lib/python3.11/site-packages/deepface/DeepFace.py", line 821, in stream
    realtime.analysis(
  File "/home/jose/anaconda3/envs/fiona_test_env/lib/python3.11/site-packages/deepface/commons/realtime.py", line 52, in analysis
    DeepFace.find(
  File "/home/jose/anaconda3/envs/fiona_test_env/lib/python3.11/site-packages/deepface/DeepFace.py", line 547, in find
    embedding_obj = represent(
                    ^^^^^^^^^^
  File "/home/jose/anaconda3/envs/fiona_test_env/lib/python3.11/site-packages/deepface/DeepFace.py", line 760, in represent
    embedding = model(img, training=False).numpy()[0].tolist()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jose/anaconda3/envs/fiona_test_env/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jose/anaconda3/envs/fiona_test_env/lib/python3.11/site-packages/deepface/basemodels/VGGFace.py", line 114, in <lambda>
    base_model_output = Lambda(lambda x: K.l2_normalize(x, axis=1), name="norm_layer")(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.UnknownError: Exception encountered when calling layer 'norm_layer' (type Lambda).

{{function_node __wrapped__Rsqrt_device_/job:localhost/replica:0/task:0/device:GPU:0}} JIT compilation failed. [Op:Rsqrt] name: 

Call arguments received by layer 'norm_layer' (type Lambda):
  • inputs=tf.Tensor(shape=(1, 4096), dtype=float32)
  • mask=None
  • training=False
  ```
  anyone knowns how can i fix this?

**Comment by serengil** [comment]
Duplicated - https://github.com/serengil/deepface/issues/957

**Comment by serengil** [comment]
Firstly, I am not having this issue with GPU but all these issues are coming from GPU.

As an improvement, not to have this issue with GPU, we may consider to disable [normalization layer in VGG-model](https://github.com/serengil/deepface/blob/master/deepface/basemodels/VGGFace.py#L147), and do it [after finding embedding](https://github.com/serengil/deepface/blob/master/deepface/basemodels/VGGFace.py#L61) in VGG module with [regular l2 normalization function of deepface](https://github.com/serengil/deepface/blob/master/deepface/commons/distance.py#L35).

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/deepface/pull/967

And release 0.0.82
