### ISSUE TITLE
installation error for 0.0.82

### ISSUE THREAD

**Issue by kkolge** [serengil/deepface#971]
Fails to install from pypi with below error 
`ERROR: Exception:
Traceback (most recent call last):
  File "/home/ketan/repos/deepface81/deep81/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ketan/repos/deepface81/deep81/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/ketan/repos/deepface81/deep81/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/ketan/repos/deepface81/deep81/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/ketan/repos/deepface81/deep81/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
`

**Comment by serengil** [comment]
Duplicated - https://github.com/serengil/deepface/issues/935
